/* The website and Paymenter share one native session and one customer profile. */
(() => {
 const client=window.NUC_BILLING;if(!client)return;
 const dialog=document.createElement('dialog');dialog.id='accountLogin';dialog.className='account-login';dialog.setAttribute('aria-labelledby','accountLoginTitle');
 dialog.innerHTML=`<div class="access-lights" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><i></i></div><section class="access-glass"><button class="access-close" type="button" aria-label="Close account popup">×</button><div class="access-brand"><img src="assets/nucaloric-wordmark.svg" alt="NUCALORIC"><span>YOUR ACCOUNT / ONE PROFILE</span></div><div class="access-heading"><span class="access-eyebrow">PICK UP WHERE YOU LEFT OFF</span><h2 id="accountLoginTitle">Welcome<br>back<span>.</span></h2><p id="accountLoginCopy">Your projects, servers and balance.<br>One account. Right here.</p></div><div id="accessProfile" hidden><span class="access-avatar"></span><strong></strong><small></small><div class="access-profile-links"><a href="dashboard.html">Open dashboard ↗</a><a href="/billing">Paymenter profile ↗</a><a href="services.html">Your servers ↗</a></div><button type="button" id="accessSignOut">Sign out</button></div><form id="accessForm"><div class="access-mode"><span>Sign in</span><a href="/billing/register">Create account ↗</a></div><label>Email address<input id="accessEmail" name="email" type="email" autocomplete="username" maxlength="254" placeholder="you@example.com" required></label><label>Password<span class="access-password"><input id="accessPassword" name="password" type="password" autocomplete="current-password" maxlength="4096" placeholder="Your password" required><button type="button" id="accessReveal" aria-label="Show password" aria-pressed="false"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/></svg></button></span></label><div class="access-options"><label><input id="accessRemember" type="checkbox">Keep me signed in</label><a href="/billing/password/request">Forgot password?</a></div><button type="submit" class="access-submit">Sign in <span>↗</span></button></form><p id="accessStatus" class="access-status" role="status" aria-live="polite"></p><a id="accessNative" class="access-native" href="/billing/nucaloric/login" hidden>Continue to account login ↗</a><div class="access-foot"><i></i><span>Your Paymenter account. Your workspace.</span><b>01 / N</b></div></section>`;
 document.body.append(dialog);
 const q=id=>document.getElementById(id);let busy=false,opener=null,opening=0;
 const button=document.createElement('button');button.type='button';button.className='nav-account';button.dataset.accountOpen='';button.setAttribute('aria-haspopup','dialog');button.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/></svg><span>Sign in</span>';
 document.querySelector('.nav-actions')?.prepend(button);
 function close(){if(busy)return;opening++;dialog.close();q('accessPassword').value='';opener?.focus({preventScroll:true});}
 async function open(){const attempt=++opening;opener=document.activeElement;q('accessStatus').textContent='Connecting to your account…';q('accessForm').querySelector('[type=submit]').disabled=true;if(!dialog.open)dialog.showModal();await client.ready;if(attempt!==opening||!dialog.open)return;if(client.state.connected){try{const session=await client.request('session');client.state.user=session.user;client.state.csrfToken=session.csrfToken;}catch{}}if(attempt!==opening||!dialog.open)return;const user=client.state.user;button.querySelector('span').textContent=user?'Account':'Sign in';q('accessForm').hidden=!!user;q('accessProfile').hidden=!user;q('accessNative').hidden=true;q('accessStatus').textContent='';q('accountLoginTitle').innerHTML=user?'Your<br>account<span>.</span>':'Welcome<br>back<span>.</span>';q('accountLoginCopy').innerHTML='Your projects, servers and balance.<br>One account. Right here.';
  if(user){q('accessProfile').querySelector('strong').textContent=user.name;q('accessProfile').querySelector('small').textContent=user.email;q('accessProfile').querySelector('.access-avatar').textContent=user.name.slice(0,1).toUpperCase();q('accountLoginCopy').textContent='Your Paymenter profile is already connected.';}
  else if(!client.state.connected){q('accessForm').hidden=true;q('accessNative').hidden=false;q('accessNative').href=client.state.externalUrl||'billing.html';q('accessStatus').textContent=client.state.externalUrl?'Continue on the live website to connect your account.':'Account login is temporarily unavailable. Try again shortly.';}
  else{try{const options=await client.request('account/options');if(options.nativeChallenge){q('accessForm').hidden=true;q('accessNative').hidden=false;q('accessStatus').textContent='Continue to complete your account verification.';}}catch(e){q('accessStatus').textContent=e.message;}}
  if(attempt!==opening||!dialog.open)return;q('accessForm').querySelector('[type=submit]').disabled=false;requestAnimationFrame(()=>user?q('accessSignOut').focus():!q('accessForm').hidden?q('accessEmail').focus():q('accessNative').focus());
 }
 dialog.querySelector('.access-close').onclick=close;dialog.addEventListener('cancel',e=>{e.preventDefault();close();});dialog.addEventListener('click',e=>{if(e.target===dialog)close();});
 q('accessReveal').onclick=()=>{const visible=q('accessPassword').type==='password';q('accessPassword').type=visible?'text':'password';q('accessReveal').setAttribute('aria-pressed',String(visible));q('accessReveal').setAttribute('aria-label',visible?'Hide password':'Show password');};
 q('accessForm').addEventListener('submit',async e=>{e.preventDefault();if(busy)return;busy=true;const submit=q('accessForm').querySelector('[type=submit]');submit.disabled=true;q('accessStatus').textContent='Connecting your account…';try{const result=await client.request('account/login',{method:'POST',body:JSON.stringify({email:q('accessEmail').value.trim(),password:q('accessPassword').value,remember:q('accessRemember').checked})});q('accessPassword').value='';if(result.redirect){const target=new URL(result.redirect,location.origin);if(target.origin!==location.origin||!target.pathname.startsWith('/billing/'))throw Error('Account verification could not be opened.');location.assign(target.href);}else{q('accessStatus').textContent='Connected. Opening your workspace…';location.reload();}}catch(error){q('accessStatus').textContent=error.message;q('accessPassword').focus();}finally{busy=false;submit.disabled=false;}});
 q('accessSignOut').onclick=async()=>{if(busy)return;busy=true;q('accessSignOut').disabled=true;try{await client.request('account/logout',{method:'POST',body:'{}'});location.reload();}catch(e){q('accessStatus').textContent=e.message;}finally{busy=false;q('accessSignOut').disabled=false;}};
 document.addEventListener('click',e=>{const target=e.target.closest('[data-account-open],a[href]');if(!target||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;const href=target.getAttribute('href')||'';if(target.hasAttribute('data-account-open')||new URL(href||'#',location.href).pathname==='/billing/nucaloric/login'){e.preventDefault();e.stopImmediatePropagation();open();}},true);
 client.ready.then(()=>{button.querySelector('span').textContent=client.state.user?'Account':'Sign in';if(new URLSearchParams(location.search).get('login')==='1')open();});
 window.NUC_ACCOUNT={open,close};
 addEventListener('nuc-account-expired',()=>{if(!dialog.open)open();});
})();
