/* Local brand assets. Displaying a provider mark does not imply a connected integration. */
(() => {
 const files={solana:'solana.svg',helius:'helius.ico',phantom:'phantom.svg',solflare:'solflare.ico',backpack:'backpack.ico',meteora:'meteora.svg',jupiter:'jupiter.ico',raydium:'raydium.ico',birdeye:'birdeye.png',paymenter:'paymenter.svg',openai:'openai.svg',claude:'claude.svg',gemini:'gemini-color.svg',grok:'grok.svg','x-social':'x.svg','x-money':'x.svg',github:'github.svg',cloudflare:'cloudflare.svg',docker:'docker.svg',tailscale:'tailscale.svg',raspberrypi:'raspberrypi.svg',supabase:'supabase.svg',vercel:'vercel.svg',netlify:'netlify.svg',postgresql:'postgresql.svg',paid:'paid.ico',pump:'pump.ico',otc:'otc.svg'};
 const native=new Set(['helius','solflare','backpack','jupiter','raydium','birdeye','paymenter','gemini','paid','pump']);
 const logo=id=>Object.hasOwn(files,id)?`<img class="service-logo${native.has(id)?' native-logo':''}" src="assets/partners/${files[id]}" alt="" aria-hidden="true" width="24" height="24">`:'';
 window.NUC_BRANDS={logo};
 const grid=document.querySelector('#developerServiceGrid');if(!grid)return;
 const search=document.querySelector('#developerServiceSearch'),category=document.querySelector('#developerServiceCategory'),count=document.querySelector('#developerServiceCount');
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let services=[];
 function render(){const q=search.value.trim().toLowerCase(),items=services.filter(s=>(category.value==='all'||s.category===category.value)&&`${s.name} ${s.role} ${s.category}`.toLowerCase().includes(q));count.textContent=`${items.length} of ${services.length} documented services · integrations planned`;grid.innerHTML=items.map(s=>`<article class="developer-service-card" data-developer-service="${esc(s.id)}"><span class="developer-brand">${logo(s.id)}<h3>${esc(s.name)}</h3></span><small>${esc(s.category)} / PLANNED</small><p>${esc(s.role)}</p><footer><a href="${esc(s.docs)}" target="_blank" rel="noopener noreferrer">OFFICIAL DOCS ↗</a><a href="status.html#service-${esc(s.id)}">STATUS ↗</a><a href="roadmap.html#phase-${s.phase}">ROADMAP ↗</a></footer></article>`).join('')||'<p>No services match. Try another name or category.</p>';}
 search.addEventListener('input',render);category.addEventListener('change',render);
 fetch('data/services.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(data=>{services=data.services;[...new Set(services.map(s=>s.category))].sort().forEach(c=>{const o=document.createElement('option');o.value=c;o.textContent=c;category.append(o);});render();}).catch(()=>{count.textContent='The service catalog could not be loaded. Refresh to try again.';});
})();
