/* Private account-owned coin memory and queued local inference. */
(() => {
 const root=document.querySelector('[data-coin-ai]'),client=window.NUC_BILLING;if(!root||!client)return;
 const $=id=>document.getElementById(id),node=(tag,text='',cls='')=>{const e=document.createElement(tag);e.textContent=text;e.className=cls;return e;};
 const activity=window.NUC_WORK_ACTIVITY('aiActivity',$('aiChat'),$('aiChatForm'));
 let sending=false;
 let creditsPerMessage=0;let coins=[],current=null,models=[],messages=[],pending=false,reading=false,activeId=null,lastTool='',sendKey=null,lastPayload=null;
 const notice=text=>{$('aiStatus').textContent=text;};
 const request=(path,data)=>client.request('ai/coins'+path,data===undefined?{}:{method:'POST',body:JSON.stringify(data)});
 const coinPath=()=>'/'+current.id;
 function fieldProfile(){return {name:$('aiName').value.trim(),ticker:$('aiTicker').value.trim(),story:$('aiStory').value.trim(),mint:$('aiMint').value.trim()||null,builders:Number($('aiBuilders').value),community:Number($('aiCommunity').value)};}
 function profileFields(coin){$('aiName').value=coin.name;$('aiTicker').value=coin.ticker;$('aiStory').value=coin.story||'';$('aiMint').value=coin.mint||'';$('aiBuilders').value=coin.revenue?.builders??40;$('aiCommunity').value=coin.revenue?.community??30;}
 function selection(){const select=$('aiCoinSelect');select.replaceChildren();for(const coin of coins){const option=node('option',coin.name+' / '+coin.ticker);option.value=coin.id;select.append(option);}select.disabled=!coins.length;if(current)select.value=current.id;}
 function busy(){pending=!!current?.pendingJob;$('aiSend').disabled=pending||sending||!current||!models.some(m=>m.installed);$('aiQuestion').disabled=!current;$('aiJobStatus').textContent=pending?'Waiting for the local model…':'Local models · short replies';$('aiModel').disabled=pending||sending;$('aiCoinSelect').disabled=sending||!coins.length;root.setAttribute('aria-busy',String(pending||sending));if(pending)activity.set('ai-waiting','Waiting for local AI','Queued or generating on Distiller · '+($('aiModel').selectedOptions[0]?.textContent||'local model'));else if(!sending)activity.set('idle');modelNotice();}
 function modelNotice(){const m=models.find(m=>m.id===$('aiModel').value);const p=document.querySelector('#aiChat > p');if(p)p.textContent=m?.id==='nucaloric:reasoning'?'Deliberate reasoning on the Distiller. Allow up to three minutes; shared resources are limited.':m?.id==='nucaloric:code'?'Local coding assistance · up to 384 output tokens. Review generated code before running it.':'Main Pi keeps your private context; Distiller runs your model. 20 messages/hour, one pending request.';if(p&&creditsPerMessage)p.textContent+=' '+creditsPerMessage+' AI credits per request; failed jobs are refunded.';}
 $('aiModel').addEventListener('change',modelNotice);
 function renderNotes(){const list=$('aiKnowledgeList');list.replaceChildren();$('aiKnowledgeCount').textContent=(current?.knowledge.length||0)+' / 30 notes';for(const note of current?.knowledge||[]){const item=node('article','','ai-note'),text=node('p',note.content),button=node('button','Remove','ai-button');button.type='button';button.addEventListener('click',async()=>{button.disabled=true;try{const d=await request(coinPath()+'/knowledge/'+note.id+'/delete',{});current=d.coin;renderNotes();notice('Knowledge note removed.');}catch(e){notice(e.message);button.disabled=false;}});item.append(text,button);list.append(item);}if(!list.children.length)list.append(node('p','Save your coin’s purpose, roadmap, decisions, and useful answers here. Future chats use relevant notes.','ai-muted'));$('aiKnowledgeSave').disabled=!current;}
 function drawMessages(){const log=$('aiChatLog'),atBottom=log.scrollHeight-log.scrollTop-log.clientHeight<100;log.replaceChildren();if(!messages.length){const empty=node('div','','ai-empty');empty.append(node('strong',current?'Give your coin a voice.':'Start with your coin.'),node('p',current?'Ask about its purpose, roadmap, or saved knowledge.':'Create a private coin workspace or import your local coin plan.'));log.append(empty);}for(const message of messages){const item=node('article','','ai-message ai-message-'+message.role);item.append(node('small',message.role==='user'?'YOU':message.model==='nucaloric:small'?'NUCALORIC / SMALL':message.model==='nucaloric:tiny'?'NUCALORIC / TINY':message.model==='nucaloric:reasoning'?'NUCALORIC / REASONING':message.model==='nucaloric:code'?'NUCALORIC / CODE':message.model?.startsWith('qwen3')?'QWEN 3 / LOCAL':'SMOLLM 2 / LOCAL'),node('pre',message.content));if(message.role==='assistant'){const save=node('button','Save to knowledge ↗','ai-button');save.type='button';save.addEventListener('click',()=>{$('aiKnowledgeText').value=message.content.slice(0,1000);$('aiKnowledgeText').focus();notice('Review this answer, then save the facts you want your coin to remember.');});item.append(save);}log.append(item);}if(atBottom||pending)log.scrollTop=log.scrollHeight;}
 function render(){selection();$('aiCreateDetails').open=!coins.length;$('aiChatTitle').textContent=current?current.name+' / AI':'Coin / AI';$('aiCoinIdentity').textContent=current?current.ticker+' · PRIVATE WORKSPACE':'Your coin workspace';$('aiEditProfile').hidden=!current;if(current){$('aiEditName').value=current.name;$('aiEditTicker').value=current.ticker;$('aiEditStory').value=current.story;$('aiEditMint').value=current.mint;$('aiEditBuilders').value=current.revenue.builders;$('aiEditCommunity').value=current.revenue.community;}busy();renderNotes();drawMessages();$('aiExport').disabled=!current;$('aiDelete').disabled=!current;$('aiTools').querySelectorAll('button').forEach(b=>b.disabled=!current);if(current?.lastError)notice(current.lastError);window.dispatchEvent(new Event('nuc-ai-workspaces'));}
 async function open(id){activeId=id;const d=await request('/'+id);if(activeId!==id)return;current=d.coin;messages=d.messages;render();}
 async function load(){const d=await request('');coins=d.coins;creditsPerMessage=d.creditsPerMessage||0;models=d.ai.models||[];$('aiModel').replaceChildren();for(const model of models){const option=node('option',model.name+(model.installed?'':' · unavailable'));option.value=model.id;option.disabled=!model.installed;$('aiModel').append(option);}$('aiEngine').textContent=d.ai.connected?'LOCAL / DISTILLER':'LOCAL AI / OFFLINE';const id=coins.some(c=>c.id===activeId)?activeId:coins[0]?.id;if(id)await open(id);else{current=null;messages=[];render();}if(!d.ai.connected)notice(d.ai.message||'The local AI worker is unavailable.');}
 $('aiCoinSelect').addEventListener('change',()=>open($('aiCoinSelect').value).catch(e=>notice(e.message)));
 $('aiCreateForm').addEventListener('submit',async e=>{e.preventDefault();$('aiCreate').disabled=true;try{const d=await request('',fieldProfile());activeId=d.coin.id;$('aiCreateDetails').open=false;await load();notice('Private coin workspace created. You can now chat and save knowledge.');}catch(error){notice(error.message);}finally{$('aiCreate').disabled=false;}});
 $('aiImport').addEventListener('click',()=>{try{const plan=JSON.parse(localStorage.getItem('nucCoinWorkbench')||'null');if(plan?.version!==1||!plan.fields)throw Error('Create and save a coin plan in the coin desk first.');profileFields({name:plan.fields.name,ticker:plan.fields.ticker,story:plan.fields.story,revenue:plan.revenue});$('aiCreateDetails').open=true;$('aiName').focus();notice('Your local plan is ready to review. Create its private AI workspace to save it to your account.');}catch(e){notice(e.message);}});
 $('aiEditForm').addEventListener('submit',async e=>{e.preventDefault();if(!current)return;try{const d=await request(coinPath(),{name:$('aiEditName').value.trim(),ticker:$('aiEditTicker').value.trim(),story:$('aiEditStory').value,mint:$('aiEditMint').value.trim()||null,builders:Number($('aiEditBuilders').value),community:Number($('aiEditCommunity').value)});current=d.coin;coins=coins.map(c=>c.id===current.id?current:c);render();notice('Coin context updated for future chats.');}catch(e){notice(e.message);}});
 $('aiChatForm').addEventListener('submit',async e=>{e.preventDefault();if(!current||pending||sending)return;const message=$('aiQuestion').value.trim();if(!message)return;const payload=JSON.stringify({message,model:$('aiModel').value});if(lastPayload!==payload){sendKey=client.uuid();lastPayload=payload;}let failure=null;sending=true;busy();activity.set('ai-queued','Sending to the Distiller','Your message and private coin context.');try{const d=await request(coinPath()+'/chat',{requestKey:sendKey,message,model:$('aiModel').value});current=d.coin;busy();$('aiQuestion').value='';lastPayload=null;notice('Your message is queued on the Distiller.');await open(current.id);}catch(error){failure=error.message;lastPayload=null;sendKey=null;try{await open(current.id);}catch{}notice(error.message);activity.set('error','Message could not be sent',error.message);}finally{sending=false;busy();if(failure&&!pending)activity.set('error','Message could not be sent',failure);}});
 $('aiQuestion').addEventListener('keydown',e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();$('aiChatForm').requestSubmit();}});
 $('aiKnowledgeForm').addEventListener('submit',async e=>{e.preventDefault();if(!current)return;$('aiKnowledgeSave').disabled=true;try{const d=await request(coinPath()+'/knowledge',{content:$('aiKnowledgeText').value.trim()});current=d.coin;$('aiKnowledgeText').value='';renderNotes();notice('Knowledge saved. The assistant can use this fact in future chats.');}catch(error){notice(error.message);$('aiKnowledgeSave').disabled=false;}});
 $('aiTools').addEventListener('click',async e=>{const button=e.target.closest('[data-ai-tool]');if(!button||!current)return;button.disabled=true;try{const data={tool:button.dataset.aiTool};if(data.tool==='allocation')data.amount=Number($('aiRevenueAmount').value);if(data.tool==='knowledge')data.query=$('aiKnowledgeQuery').value;const d=await request(coinPath()+'/tools',data);lastTool=d.content;$('aiToolResult').textContent=d.content;$('aiToolResult').hidden=false;$('aiSaveTool').hidden=false;notice('Tool result ready.');}catch(error){notice(error.message);}finally{button.disabled=false;}});
 $('aiSaveTool').addEventListener('click',()=>{$('aiKnowledgeText').value=lastTool.slice(0,1000);$('aiKnowledgeText').focus();notice('Review the tool result before saving it to knowledge.');});
 $('aiExport').addEventListener('click',async()=>{if(!current)return;try{const d=await request(coinPath()),url=URL.createObjectURL(new Blob([JSON.stringify({format:'nucaloric-coin-ai',version:1,...d},null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=current.ticker.toLowerCase()+'-ai-workspace.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notice('Private coin context, knowledge, and chat history exported.');}catch(e){notice(e.message);}});
 $('aiDelete').addEventListener('click',async()=>{if(!current||!confirm('Delete this private coin AI workspace, its knowledge and chat history? Your coin plan and website will remain.'))return;try{await request(coinPath()+'/delete',{});activeId=null;current=null;await load();notice('Private coin AI workspace deleted.');}catch(e){notice(e.message);}});
 setInterval(async()=>{if(!pending||!current||reading||document.hidden)return;reading=true;const id=current.id;try{const d=await request('/'+id);if(activeId!==id)return;const changed=JSON.stringify(messages)!==JSON.stringify(d.messages);current=d.coin;messages=d.messages;busy();if(changed)drawMessages();if(!pending)notice(current.lastError||'Reply ready. Save useful facts to grow your coin’s knowledge.');}catch(e){notice(e.message);activity.set('reconnecting','Checking your AI reply','Connection interrupted · retrying the saved job.');}finally{reading=false;}},5000);
 window.NUC_COIN_WORKSPACES={list:()=>structuredClone(coins),selected:()=>current?.id||null,select:async id=>{if(sending)throw Error('Wait for your message to be sent before changing coin workspace.');if(!coins.some(c=>c.id===id))throw Error('Choose your private coin workspace.');await open(id);}};
 client.ready.then(async state=>{if(!state.connected||!state.user){$('aiGate').hidden=false;$('aiWorkspace').hidden=true;const text=state.externalUrl?'Open your Pi-hosted account to use the local models.':'Sign in to use your private coin assistant.';$('aiGateText').textContent=text;$('aiSignIn').href=state.externalUrl||'/billing/nucaloric/login';return;}$('aiGate').hidden=true;$('aiWorkspace').hidden=false;const params=new URLSearchParams(location.search);if(params.get('name'))profileFields({name:params.get('name').slice(0,60),ticker:(params.get('ticker')||'COIN').replace(/[^a-z0-9]/gi,'').slice(0,10),mint:params.get('mint')||'',story:'',revenue:{builders:40,community:30}});activity.set('connecting','Loading your coin workspace','Reading private context and available models.');try{await load();}catch(e){activity.set('error','AI workspace unavailable',e.message);notice(e.message);}});
})();
