/* Native-session checkout. Wallet signatures prove ownership; the backend verifies receipts. */
(() => {
 const client=window.NUC_BILLING;if(!client)return;
 const providers=[];let catalog=null,balance={ai:0,server:0},intent=null,selection=null,busy=false,evm=null,btc=null;
 const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
 const api=(p,data)=>client.request('commerce'+p,data===undefined?{}:{method:'POST',body:JSON.stringify(data)});
 const dollar=c=>'$'+(c/100).toFixed(2);
 const announce=e=>{if(e.detail?.provider?.request&&!providers.some(p=>p.provider===e.detail.provider)){providers.push(e.detail);fillWallets();}};
 window.addEventListener('eip6963:announceProvider',announce);window.dispatchEvent(new Event('eip6963:requestProvider'));
 let box,form,chains,wallets,bundles,notice,review,pay,activity,stats,links;
 function say(message){if(notice)notice.textContent=message;}
 function fillWallets(){if(!wallets)return;wallets.replaceChildren();const list=chains.value==='solana'?(window.NUC_WALLET?.targets||[]):chains.value==='bitcoin'?[{id:'unisat',name:'UniSat · Bitcoin'}]:providers.map((p,i)=>({id:String(i),name:p.info.name}));if(['ethereum','robinhood'].includes(chains.value)&&window.ethereum?.request&&!providers.some(p=>p.provider===window.ethereum))list.push({id:'injected',name:window.ethereum.isBraveWallet?'Brave Wallet':window.ethereum.isPhantom?'Phantom EVM':'Browser EVM wallet'});if(!list.length)list.push({id:'missing',name:'Install an EVM wallet to continue'});for(const p of list){const option=node('option',p.name);option.value=p.id;wallets.append(option);}}
 function clearReview(){intent=null;review.hidden=true;pay.disabled=false;}
 async function link(chain){
  if(chain==='solana'){const w=window.NUC_WALLET;if(!w)throw Error('Wallet tools are still loading. Try again.');await w.connect(wallets.value);if(!w.state.connected||w.state.provider!==wallets.value)throw Error('Connect the selected Solana wallet first.');if(!w.state.verified)await w.link();if(!w.state.verified)throw Error('Approve the account-link signature in your wallet, then try again.');return w.state.address;}
  let address,signature;
  if(chain==='bitcoin'){btc=window.unisat;if(!btc?.requestAccounts||!btc.signMessage||!btc.sendBitcoin)throw Error('Install UniSat or open this HTTPS site in its Bitcoin wallet browser.');const net=await btc.getNetwork();if(net!=='livenet')throw Error('Select Bitcoin mainnet in your wallet.');[address]=await btc.requestAccounts();}
  else{evm=wallets.value==='injected'?window.ethereum:providers[Number(wallets.value)]?.provider;if(!evm?.request)throw Error('Install a compatible EVM wallet, then reload this page.');[address]=await evm.request({method:'eth_requestAccounts'});address=address?.toLowerCase();await switchChain(chain);}
  const linked=await api('/wallets');if(linked.wallets.some(w=>w.chain===chain&&w.address===address))return address;
  const challenge=await api('/wallets/challenge',{chain,address,provider:chain==='bitcoin'?'unisat':'evm'});
  if(chain==='bitcoin')signature=await btc.signMessage(challenge.message,'bip322-simple');else signature=await evm.request({method:'personal_sign',params:['0x'+Array.from(new TextEncoder().encode(challenge.message),b=>b.toString(16).padStart(2,'0')).join(''),address]});
  await api('/wallets/verify',{id:challenge.id,signature});return address;
 }
 async function switchChain(chain){const cfg=catalog.chains.find(c=>c.id===chain),id='0x'+cfg.chainId.toString(16);try{await evm.request({method:'wallet_switchEthereumChain',params:[{chainId:id}]});}catch(e){if(e.code!==4902||chain!=='robinhood')throw e;await evm.request({method:'wallet_addEthereumChain',params:[{chainId:id,chainName:'Robinhood Chain',nativeCurrency:{name:'Ether',symbol:'ETH',decimals:18},rpcUrls:['https://rpc.mainnet.chain.robinhood.com'],blockExplorerUrls:['https://robinhoodchain.blockscout.com']}]});await evm.request({method:'wallet_switchEthereumChain',params:[{chainId:id}]});}if((await evm.request({method:'eth_chainId'})).toLowerCase()!==id)throw Error('Select the payment network in your wallet.');}
 async function run(fn){if(busy)return;busy=true;form?.querySelectorAll('button,select').forEach(b=>b.disabled=true);pay.disabled=true;if(box)box.querySelector('[data-close]').disabled=true;try{await fn();}catch(e){say(e.code===4001?'Wallet request declined. No credits have been deducted.':e.message||'The wallet request failed. Your receipt is preserved.');}finally{busy=false;form?.querySelectorAll('button,select').forEach(b=>b.disabled=!client.state.user||!catalog.enabled);pay.disabled=!intent;if(box)box.querySelector('[data-close]').disabled=false;}}
 function units(value,decimals){const n=BigInt(value),factor=10n**BigInt(decimals),fraction=(n%factor).toString().padStart(decimals,'0').replace(/0+$/,'');return (n/factor).toString()+(fraction?'.'+fraction:'');}
 function saveReceipt(id,signature){try{localStorage.setItem('nucCommerce:'+id,JSON.stringify({signature}));}catch{}}
 async function check(id,signature){const result=await api('/intents/'+id+'/confirm',signature?{signature}:{});if(result.status==='credited'){say(result.purchaseError?'Payment confirmed. Your server credits are retained: '+result.purchaseError:result.workspaceId?'Payment confirmed. Your monthly server is ready in Services.':'Payment confirmed. Credits are available.');window.dispatchEvent(new Event('nuc-commerce-updated'));}else say(result.message||'Waiting for blockchain confirmation. The server checks your saved receipt automatically.');await refresh();return result;}
 async function refresh(){if(!client.state.user||!box)return;const [d,linked]=await Promise.all([api(''),api('/wallets')]);balance=d.balances;stats.textContent=dollar(balance.server)+' server balance · '+balance.ai.toLocaleString()+' high AI credits';links.replaceChildren();for(const w of linked.wallets){if(w.chain==='solana')continue;const row=node('div',undefined,'commerce-receipt'),copy=node('small',w.chain+' · '+w.address.slice(0,8)+'…'+w.address.slice(-6)),button=node('button','Unlink');button.type='button';button.addEventListener('click',()=>run(async()=>{await api('/wallets/unlink',{chain:w.chain,address:w.address});await refresh();say('Payment wallet unlinked from your account. Submitted receipts are preserved.');}));row.append(copy,button);links.append(row);}activity.replaceChildren();for(const p of d.pending){const row=node('div',undefined,'commerce-receipt'),copy=node('small',catalog.bundles[p.bundle].name+' · '+p.chain+' · '+p.status);const button=node('button',p.signature?'Check confirmation':'Enter transaction receipt');button.type='button';button.addEventListener('click',()=>run(async()=>{let signature=p.signature;if(!signature)try{signature=JSON.parse(localStorage.getItem('nucCommerce:'+p.id)||'null')?.signature;}catch{}if(!signature)signature=prompt('Paste the transaction hash from your wallet. This is a public receipt, never a seed phrase.');if(!signature)return;saveReceipt(p.id,signature);await check(p.id,signature);}));row.append(copy,button);activity.append(row);}for(const u of d.usage){activity.append(node('small',u.model.replace('nucaloric:','')+' · '+u.input_tokens+' input + '+u.output_tokens+' output · '+u.charged+' credits · '+u.status,'commerce-usage'));}const a=document.querySelector('#aiCreditBalance'),s=document.querySelector('#serverCreditBalance');if(a)a.textContent=balance.ai.toLocaleString();if(s)s.textContent=dollar(balance.server);const policy=document.querySelector('#creditPolicy');if(policy)policy.textContent='Tiny + Small are free. Higher AI: $0.50 / 1,000 processed tokens. Basic $1.50 / month · Full $2 / month.';}
 async function prepare(bundle,server){clearReview();say('Connect your wallet and approve the account-link message.');const chain=chains.value,address=await link(chain);const d=await api('/intents',{requestKey:client.uuid(),bundle,chain,address,...(server?{server}:{})});intent=d.intent;const cfg=catalog.chains.find(c=>c.id===chain);review.querySelector('pre').textContent=catalog.bundles[bundle].name+' · '+dollar(intent.usdCents)+'\n'+units(intent.amount,intent.decimals)+' '+intent.asset+' + wallet network fee\nNetwork: '+cfg.name+' mainnet\nFrom: '+intent.payer+'\nTo: '+intent.treasury+'\nQuote expires: '+new Date(intent.expiresAt).toLocaleTimeString()+'\n'+(chain==='bitcoin'?'Six confirmations required.':'Blockchain finality required.')+'\n'+(server?'Starts one prepaid calendar month when allocated. Renew manually.':'Server balance is USD credit; high AI uses processed tokens.');review.hidden=false;pay.disabled=false;say('Review the destination and amount. Approve the transfer only when ready.');await refresh();}
 function solSignature(base64){const bytes=Uint8Array.from(atob(base64),c=>c.charCodeAt(0)).slice(1,65);let n=0n;for(const b of bytes)n=n*256n+BigInt(b);const alphabet='123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';let text='';while(n){text=alphabet[Number(n%58n)]+text;n/=58n;}for(const b of bytes){if(b)break;text='1'+text;}return text;}
 async function approve(){if(!intent)throw Error('Review a payment first.');const p=intent;if(Date.now()>=new Date(p.expiresAt).getTime())throw Error('This quote expired. Review a new payment before approving.');let signature;say('Approve this transfer in your wallet.');
  if(p.chain==='solana'){if(window.NUC_WALLET.state.address!==p.payer)throw Error('Wallet account changed. Review a new payment.');const signedTransaction=await window.NUC_WALLET.signTransaction(p.transaction,'mainnet-beta');signature=solSignature(signedTransaction);saveReceipt(p.id,signature);try{await api('/intents/'+p.id+'/submit',{signedTransaction});}catch(e){say('Submission needs a retry. Your signed receipt is saved; check confirmation below.');await refresh();throw e;}}
  else if(p.chain==='bitcoin'){if(await btc.getNetwork()!=='livenet'||!(await btc.getAccounts()).includes(p.payer))throw Error('Bitcoin account or network changed. Review a new payment.');signature=await btc.sendBitcoin(p.treasury,Number(p.amount));saveReceipt(p.id,signature);await api('/intents/'+p.id+'/submit',{signature});}
  else{await switchChain(p.chain);if(!(await evm.request({method:'eth_accounts'})).some(a=>a.toLowerCase()===p.payer))throw Error('Wallet account changed. Review a new payment.');signature=await evm.request({method:'eth_sendTransaction',params:[p.evmTransaction]});saveReceipt(p.id,signature);await api('/intents/'+p.id+'/submit',{signature});}
  clearReview();say('Payment submitted. Waiting for blockchain confirmation…');await refresh();for(let i=0;i<6;i++){await new Promise(r=>setTimeout(r,4000));if((await check(p.id,signature)).status==='credited')break;}
 }
 function mount(){const credits=document.querySelector('#credits'),billing=document.querySelector('.billing-overview');if(!credits&&!billing)return;box=node('section',undefined,'commerce-panel');box.id='cryptoCheckout';box.innerHTML='<div class="commerce-heading"><span>WALLET CHECKOUT</span><a href="services.html">Your services ↗</a></div><h3>Your compute. Your balance.</h3><p>Tiny + Small AI are free. Higher models cost $0.50 per 1,000 processed tokens. Servers are $1.50 or $2 per month.</p><strong class="commerce-balance"></strong><form class="commerce-form"><label>Purchase<select name="bundle"></select></label><label>Network<select name="chain"></select></label><label>Wallet<select name="wallet"></select></label><button type="submit">Connect & review payment ↗</button></form><div class="commerce-review" hidden><strong>Review before you approve</strong><pre></pre><div><button type="button" data-approve>Approve in wallet ↗</button><button type="button" data-close>Cancel review</button></div></div><p class="commerce-notice" role="status" aria-live="polite"></p><details><summary>Receipts & token usage</summary><div class="commerce-activity"></div></details><details><summary>Linked payment wallets</summary><div class="commerce-wallet-links"></div></details><small>Network fees are separate. Each transfer needs your wallet approval. A submitted payment is checked automatically; closing the page does not cancel it.</small>';
 if(credits)credits.append(box);else billing.after(box);form=box.querySelector('form');chains=form.elements.chain;wallets=form.elements.wallet;bundles=form.elements.bundle;notice=box.querySelector('.commerce-notice');review=box.querySelector('.commerce-review');pay=box.querySelector('[data-approve]');activity=box.querySelector('.commerce-activity');links=box.querySelector('.commerce-wallet-links');stats=box.querySelector('.commerce-balance');
 for(const [id,b] of Object.entries(catalog.bundles)){const o=node('option',(b.kind==='server'?'Server credits · ':'')+b.name+' · '+dollar(b.usdCents));o.value=id;bundles.append(o);}for(const c of catalog.chains){const o=node('option',c.name+' · '+c.asset);o.value=c.id;chains.append(o);}fillWallets();form.addEventListener('submit',e=>{e.preventDefault();selection=null;run(()=>prepare(bundles.value));});chains.addEventListener('change',()=>{clearReview();fillWallets();});wallets.addEventListener('change',clearReview);bundles.addEventListener('change',clearReview);pay.addEventListener('click',()=>run(approve));box.querySelector('[data-close]').addEventListener('click',()=>{clearReview();say('Review closed. No wallet transaction was requested.');});
 if(!client.state.user){form.querySelector('button').disabled=true;say('Sign in to fund your server or high AI balance.');}else if(!catalog.enabled){form.querySelector('button').disabled=true;say('Checkout is temporarily unavailable. Your balances are preserved.');}
 }
 const ready=client.ready.then(async()=>{if(!client.state.connected)return;catalog=await api('/catalog');mount();await refresh();}).catch(e=>say(e.message));
 window.NUC_COMMERCE={ready,get catalog(){return catalog;},get balance(){return balance;},async purchaseServer(tier,plan,key){await ready;selection={tier,plan};if(balance.server>=catalog.tiers[tier].priceCents){const d=await api('/servers',{requestKey:key,tier,plan});await refresh();window.dispatchEvent(new Event('nuc-commerce-updated'));return d;}bundles.value='server-'+tier;await run(()=>prepare('server-'+tier,{tier,plan}));if(!intent)throw Error(notice.textContent||'Payment review could not be prepared.');box.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'center'});return {needsPayment:true};},refresh};
 window.addEventListener('nuc-commerce-updated',()=>refresh().catch(()=>{}));
})();
