/* A coin collection, saved shelf and inspector over one live market observation. */
(() => {
 const root=document.querySelector('.atlas-workspace');if(!root)return;
 const q=s=>document.querySelector(s),node=(tag,cls,text)=>{const e=document.createElement(tag);e.className=cls;if(text!==undefined)e.textContent=text;return e;};
 const results=q('#marketResults'),search=q('#liveMarketSearch'),savedOnly=q('#marketWatchOnly'),dialog=q('[data-pool-inspector]'),reduced=matchMedia('(prefers-reduced-motion:reduce)');let state={state:'loading',visiblePairs:[],saved:[]},inspected=null,opener=null;
 const num=v=>v===null||v===undefined||v===''||!Number.isFinite(Number(v))?null:Number(v);
 const usd=v=>num(v)===null?'Unavailable':new Intl.NumberFormat(undefined,{style:'currency',currency:'USD',maximumFractionDigits:Number(v)<1?8:2,notation:Number(v)>=100000?'compact':'standard'}).format(Number(v));
 const change=v=>num(v)===null?'Unavailable':(Number(v)>0?'+':'')+Number(v).toFixed(2)+'%';
 function art(pair,cls){const box=node('div',cls);box.innerHTML=window.NUC_TOKEN_ART?.html(pair,'token-profile')||'';return box;}
 function scope(){q('[data-market-browse]').setAttribute('aria-pressed',String(!savedOnly.checked));q('[data-market-watchlist]').setAttribute('aria-pressed',String(savedOnly.checked));q('[data-open-watch]').setAttribute('aria-pressed',String(savedOnly.checked));q('[data-market-scope]').textContent=savedOnly.checked?'MY SAVED COINS':'ALL OBSERVATIONS';q('[data-explore-clear]').hidden=!search.value;}
 let layout='grid';try{layout=localStorage.getItem('nucExploreView')==='compact'?'compact':'grid';}catch{}
 function setLayout(value){layout=value;results.classList.toggle('compact',value==='compact');root.querySelectorAll('[data-market-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.marketView===value)));try{localStorage.setItem('nucExploreView',value);}catch{}}
 root.querySelectorAll('[data-market-view]').forEach(b=>b.addEventListener('click',()=>setLayout(b.dataset.marketView)));setLayout(layout);
 q('[data-market-browse]').addEventListener('click',()=>{savedOnly.checked=false;search.value='';q('[data-market-refresh]').click();scope();});q('[data-open-watch]').addEventListener('click',()=>{q('[data-market-watchlist]').click();q('#collection').scrollIntoView({block:'start',behavior:reduced.matches?'auto':'smooth'});});
 search.addEventListener('input',scope);q('#liveMarketForm').addEventListener('submit',scope);q('[data-market-watchlist]').addEventListener('click',scope);root.querySelectorAll('[data-launchpad]').forEach(b=>b.addEventListener('click',scope));
 q('[data-explore-clear]').addEventListener('click',()=>{search.value='';search.dispatchEvent(new Event('input',{bubbles:true}));search.focus();});
 results.addEventListener('click',event=>{if(event.target.closest('[data-explore-retry]'))q('[data-market-refresh]').click();if(event.target.closest('[data-explore-reset-filters]'))q('[data-launchpad=all]').click();const button=event.target.closest('[data-pool-inspect]');if(button){opener=button;inspected=button.dataset.poolInspect;renderInspector();dialog.showModal();q('[data-inspector-close]').focus();}});
 function renderInspector(){
  const body=q('[data-inspector-body]'),pair=state.state==='ready'&&(state.allPairs||state.visiblePairs).find(x=>x.pairAddress===inspected),focused=document.activeElement?.dataset.inspectorAction;
  const existing=body.querySelector('[data-inspector-chart]');
  if(!pair){existing?._chart?.destroy();body.replaceChildren();const h=node('h2','','Observation unavailable');h.id='inspectorTitle';body.append(h,node('p','','Refresh the collection for a current observation.'));return;}
  const chart=existing?.dataset.inspectorChart===pair.pairAddress?existing:node('div','inspector-chart-slot');if(chart!==existing)existing?._chart?.destroy();chart.dataset.inspectorChart=pair.pairAddress;body.replaceChildren();
  const identity=node('div','inspector-identity'),title=node('h2','',pair.baseToken.name);title.id='inspectorTitle';identity.append(art(pair,'inspector-art'),node('span','',pair.baseToken.symbol+' / '+(pair.quoteToken?.symbol||'Unknown')+' · '+pair.dexId),title);
  const price=node('div','inspector-price');price.append(node('span','','OBSERVED PRICE / USD'),node('b','',usd(pair.priceUsd)),node('small','',change(pair.priceChange?.h24)+' / 24H CHANGE'));
  const metrics=node('dl','inspector-metrics'),integer=v=>num(v)===null?'Unavailable':Number(v).toLocaleString();
  for(const [label,value]of [['Liquidity',usd(pair.liquidity?.usd)],['24h volume',usd(pair.volume?.h24)],['Market cap',usd(pair.marketCap)],['Fully diluted value',usd(pair.fdv)],['24h buys / sells',integer(pair.txns?.h24?.buys)+' / '+integer(pair.txns?.h24?.sells)],['Pool created',Number.isFinite(pair.pairCreatedAt)?new Date(pair.pairCreatedAt).toLocaleDateString():'Unavailable']]){const e=node('div','');e.append(node('dt','',label),node('dd','',value));metrics.append(e);}
  const addresses=node('dl','inspector-addresses');for(const [label,value]of [['TOKEN MINT',pair.baseToken.address],['POOL ADDRESS',pair.pairAddress]]){const row=node('div','');row.append(node('dt','',label),node('dd','',value));addresses.append(row);}
  const links=node('div','inspector-links');for(const [label,url]of [['View token on Solscan ↗','https://solscan.io/token/'+encodeURIComponent(pair.baseToken.address)],['Pool on DEX Screener ↗','https://dexscreener.com/solana/'+encodeURIComponent(pair.pairAddress)],...(pair.info?.websites||[]).slice(0,2).map(w=>[w.label||'Website ↗',w.url]),...(pair.info?.socials||[]).slice(0,2).map(w=>[w.type+' ↗',w.url])]){try{const u=new URL(url);if(u.protocol!=='https:'||u.username||u.password)continue;const link=node('a','',label);link.href=u.href;link.target='_blank';link.rel='noopener noreferrer';links.append(link);}catch{}}
  const actions=node('div','inspector-actions'),save=node('button','',state.saved.some(x=>x.pair===pair.pairAddress)?'Remove from saved ★':'Save this coin ☆');save.type='button';save.dataset.inspectorAction='save';save.setAttribute('aria-pressed',String(state.saved.some(x=>x.pair===pair.pairAddress)));save.addEventListener('click',()=>{window.NUC_MARKET.toggleSaved(pair.pairAddress);q('[data-inspector-action=save]')?.focus({preventScroll:true});});
  const full=node('a','','Open coin profile ↗');full.href='coin.html?pair='+encodeURIComponent(pair.pairAddress);actions.append(save,full);
  body.append(identity,price,chart,metrics,addresses,links,actions,node('p','inspector-notice','DEX Screener pool observation · '+(state.checkedAt?new Date(state.checkedAt).toLocaleTimeString():'time unavailable')+'. Refresh the collection for new data.'));
  if(!chart._chart)chart._chart=window.NUC_POOL_CHART?.mount(chart,pair);if(focused)body.querySelector(`[data-inspector-action="${focused}"]`)?.focus({preventScroll:true});
 }
 q('[data-inspector-close]').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{const chart=q('[data-inspector-chart]');chart?._chart?.destroy();q('[data-inspector-body]').replaceChildren();const current=opener&&results.querySelector(`[data-pool-inspect="${opener.dataset.poolInspect}"]`);(current||search).focus({preventScroll:true});});dialog.addEventListener('click',e=>{const r=dialog.getBoundingClientRect();if(e.target===dialog&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))dialog.close();});
 function widgets(next){state=next;const shelf=q('[data-module-watchlist]'),pulse=q('[data-market-pulse]');shelf.replaceChildren();pulse.replaceChildren();if(!state.saved.length)shelf.append(node('div','atlas-shelf-empty','Keep the ones that catch your eye. Save a coin from the collection to find it here.'));
  for(const record of state.saved){const pair=state.visiblePairs.find(p=>p.pairAddress===record.pair)||{baseToken:{symbol:record.symbol||record.name},info:{imageUrl:record.imageUrl}},row=node('div','atlas-saved-row'),link=node('a','',record.name);link.href='coin.html?pair='+encodeURIComponent(record.pair);const remove=node('button','','×');remove.type='button';remove.setAttribute('aria-label','Remove '+record.name+' from saved coins');remove.addEventListener('click',()=>{window.NUC_MARKET.removeSaved(record.pair);(shelf.querySelector('button')||q('[data-open-watch]')).focus({preventScroll:true});});row.append(art(pair,'atlas-saved-art'),link,remove);shelf.append(row);}
  const records=state.state==='ready'?state.visiblePairs.filter(p=>num(p.volume?.h24)!==null).sort((a,b)=>Number(b.volume.h24)-Number(a.volume.h24)).slice(0,3):[],max=records.length?Math.max(0,Number(records[0].volume.h24)):0;
  if(!records.length)pulse.append(node('p','module-placeholder',state.state==='loading'?'Reading the market…':'No volume observation in this view.'));
  for(const pair of records){const row=node('div','atlas-pulse-row'),head=node('div',''),bar=node('div','atlas-pulse-bar');head.append(node('b','',pair.baseToken.symbol),node('span','',usd(pair.volume.h24)));bar.setAttribute('aria-hidden','true');for(let i=0;i<24;i++)bar.append(node('i',max&&i<Math.round(Number(pair.volume.h24)/max*24)?'filled':''));row.append(head,bar);pulse.append(row);}if(dialog.open)renderInspector();scope();
 }
 addEventListener('nuc:market-update',e=>widgets(e.detail));widgets(window.NUC_MARKET?.getState()||state);
 const motion=q('[data-explore-motion]');function syncMotion(){const paused=window.NUC_DOTS?.isPaused()||false;motion.disabled=reduced.matches;motion.setAttribute('aria-pressed',String(paused));motion.textContent=reduced.matches?'Motion reduced':paused?'Resume motion':'Pause motion';root.dataset.motionPaused=String(paused||reduced.matches);}
 motion.addEventListener('click',()=>{window.NUC_DOTS?.setPaused(!window.NUC_DOTS.isPaused());syncMotion();});reduced.addEventListener('change',syncMotion);syncMotion();
})();
