/* Private account documents and owned server assets. Contents stay in memory. */
(() => {
 const client=window.NUC_BILLING,inspector=document.querySelector('.desk-inspector');if(!client||!inspector)return;
 const el=(tag,cls,text)=>{const n=document.createElement(tag);n.className=cls||'';if(text!==undefined)n.textContent=text;return n;},size=n=>n>=1048576?(n/1048576).toFixed(2)+' MiB':n>=1024?(n/1024).toFixed(1)+' KiB':n+' B',q=id=>document.getElementById(id);
 const detail=el('details','desk-detail');detail.id='deskFiles';detail.hidden=true;detail.innerHTML='<summary>Files workspace <span>＋</span></summary><div class="desk-detail-body files-space"><header class="files-heading"><div><h3>A place for the pieces.</h3><p>Keep your files close to your work.</p></div><button type="button" id="filesRefresh">Refresh ↻</button></header><div class="files-toolbar"><select id="filesTarget" aria-label="File storage"><option value="account">Account documents · private</option></select><button type="button" id="filesNew">New file ＋</button><button type="button" id="filesFolder">Folder ＋</button><label class="files-upload">Upload ↑<input type="file" id="filesUpload" multiple aria-label="Upload files"></label></div><div class="files-storage" id="filesStorage"></div><nav class="files-breadcrumb" id="filesBreadcrumb" aria-label="File location"></nav><div class="files-list" id="filesList"></div><div class="files-drop" id="filesDrop">Drop files here to upload them to the selected storage.</div><p class="files-notice" id="filesNotice" role="status" aria-live="polite"></p></div>';
 inspector.append(detail);const nav=el('button');nav.type='button';nav.dataset.deskOpen='deskFiles';nav.innerHTML='<span aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4"><path d="M4 6h6l2 3h8v11H4Z"/><path d="M4 9V4h7l2 2h7v3"/></svg></span><b>Files</b>';nav.onclick=()=>window.NUC_DEV_PANELS.open('deskFiles');document.querySelector('.desk-nav').append(nav);
 const dialog=el('dialog','file-editor');dialog.id='fileEditor';dialog.setAttribute('aria-labelledby','fileEditorTitle');dialog.innerHTML='<form id="fileEditorForm"><header><h3 id="fileEditorTitle">Edit file</h3><button type="button" id="fileEditorClose" aria-label="Close file editor">×</button></header><div class="file-editor-body"><label id="fileNameLabel">File path<input id="fileEditorName" maxlength="160" required placeholder="notes.txt"></label><label id="fileContentLabel">Contents<textarea id="fileEditorContent" spellcheck="false" aria-label="File contents"></textarea></label><p id="fileEditorHint"></p><p id="fileEditorStatus" role="status" aria-live="polite"></p></div><footer><button type="button" id="fileEditorCancel">Cancel</button><button type="submit" id="fileEditorSave">Save file ↗</button></footer></form>';document.body.append(dialog);
 let rows=[],workspaces=[],directory='',version=0,busy=false,editor=null,question=null,opened=false;
 const target=()=>q('filesTarget').value;
 function notice(text){q('filesNotice').textContent=text;}
 function controls(){for(const n of detail.querySelectorAll('button,select,input'))n.disabled=busy||!client.state.user;q('filesFolder').hidden=target()==='account';q('filesUpload').accept=target()==='account'?'.txt,.md,.json,.csv,.js,.css,.html,.svg':'.html,.css,.js,.mjs,.json,.svg,.png,.jpg,.jpeg,.ico,.webp,.txt,.woff,.woff2';}
 function encoded(text){const bytes=new TextEncoder().encode(text);let raw='';for(let i=0;i<bytes.length;i+=8192)raw+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(raw);}
 async function api(action,payload={},storage=target()){if(storage==='account'){if(action==='list')return client.request('files');if(action==='read')return client.request('files/'+encodeURIComponent(payload.path));if(action==='write')return client.request('files/'+encodeURIComponent(payload.path),{method:'POST',body:JSON.stringify({content:payload.content})});if(action==='delete')return client.request('files/'+encodeURIComponent(payload.path)+'/delete',{method:'POST',body:'{}'});throw Error('Folders and renaming are available for server files.');}return client.request('workspaces/'+encodeURIComponent(storage)+'/files'+(action==='list'?'':'/'+action),action==='list'?{}:{method:'POST',body:JSON.stringify(payload)});}
 function render(data){if(target()==='account'){rows=(data.files||[]).map(f=>({...f,path:f.name,type:'file',editable:true,managed:false}));directory='';q('filesStorage').textContent=rows.length+' / '+(data.limit||20)+' private documents · up to '+(data.maxFileChars||20000).toLocaleString()+' characters each. These are separate from public website files.';}else{rows=data.entries||[];const s=data.storage;q('filesStorage').replaceChildren(el('span','',size(s.usedBytes)+' / '+size(s.limitBytes)+' · '+size(s.appBytes)+' apps · '+size(s.availableBytes)+' available'));const meter=el('meter');meter.min=0;meter.max=s.limitBytes;meter.value=s.usedBytes;meter.setAttribute('aria-label','Server disk used');q('filesStorage').append(meter);}
  const crumb=q('filesBreadcrumb');crumb.replaceChildren();const home=el('button','',target()==='account'?'Private documents':'Server files');home.type='button';home.onclick=()=>{directory='';renderRows();};crumb.append(home);renderRows();controls();
 }
 function renderRows(){const list=q('filesList');list.replaceChildren();const crumb=q('filesBreadcrumb');while(crumb.children.length>1)crumb.lastChild.remove();if(directory){let path='';for(const segment of directory.split('/')){path+=(path?'/':'')+segment;const current=path,b=el('button','',segment);b.type='button';b.onclick=()=>{directory=current;renderRows();};crumb.append(el('span','','/'),b);}}
  const visible=rows.filter(r=>r.path.startsWith(directory?directory+'/':'')&&!r.path.slice(directory?directory.length+1:0).includes('/')).sort((a,b)=>(a.type==='folder'?-1:1)-(b.type==='folder'?-1:1)||a.path.localeCompare(b.path));
  if(!visible.length){list.append(el('p','files-empty','No files here yet. Add a document or upload the pieces for your website.'));return;}
  for(const file of visible){const row=el('div','files-row'),info=el('div','files-row-info'),name=el('button','',file.path.split('/').pop());name.type='button';name.onclick=()=>file.type==='folder'?(directory=file.path,renderRows()):openEditor(file);info.append(name,el('small','',file.type==='folder'?(file.managed?'Installed apps · managed by store':'Folder'):size(file.bytes)+(file.managed?' · installed app':target()==='account'?' · private':' · website file')));const actions=el('div','files-row-actions');
   if(file.type==='file'){const download=el('button','','↓');download.type='button';download.setAttribute('aria-label','Download '+file.path);download.onclick=()=>downloadFile(file);actions.append(download);}
   if(!file.managed){if(target()!=='account'&&file.type==='file'&&file.path!=='index.html'){const rename=el('button','','Rename');rename.type='button';rename.onclick=()=>openMutation('rename',file);actions.append(rename);}if(file.path!=='index.html'){const remove=el('button','','Delete');remove.type='button';remove.setAttribute('aria-label','Delete '+file.path);remove.onclick=()=>openMutation('delete',file);actions.append(remove);}}
   row.append(el('span','files-row-icon',file.type==='folder'?'▱':'▤'),info,actions);list.append(row);
  }controls();
 }
 async function refresh(){const n=++version,storage=target();notice('Reading your files…');if(!client.state.user){q('filesList').replaceChildren(el('p','files-empty','Sign in to see your private documents and server files.'));const b=el('button','setup-link-button','Sign in ↗');b.type='button';b.dataset.accountOpen='';q('filesList').append(b);notice('');controls();return;}
  try{const data=await api('list',{},storage);if(n!==version||storage!==target())return;render(data);notice(storage==='account'?'Private account files can also be used as AI attachments.':'Changes to server files are published immediately. The apps folder is managed by the store.');}catch(e){if(n!==version)return;q('filesList').replaceChildren(el('p','files-empty',e.message));notice(e.message);controls();}
 }
 function resetDialog(){q('fileNameLabel').hidden=false;q('fileContentLabel').hidden=false;q('fileEditorStatus').textContent='';q('fileEditorName').readOnly=false;q('fileEditorContent').readOnly=false;q('fileEditorSave').hidden=false;q('fileEditorSave').disabled=false;q('fileEditorHint').textContent='';}
 function close(){if(busy)return;if(question){question.resolve(false);question=null;}editor=null;dialog.close();}
 q('fileEditorClose').onclick=close;q('fileEditorCancel').onclick=close;dialog.addEventListener('cancel',e=>{e.preventDefault();close();});
 async function openEditor(file=null){if(busy)return;resetDialog();const storage=target();editor={mode:'write',storage,path:file?.path||'',revision:file?.revision||null};q('fileEditorTitle').textContent=file?'Edit '+file.path.split('/').pop():'A new file';q('fileEditorName').value=file?.path||(directory?directory+'/':'');q('fileEditorName').readOnly=!!file;q('fileEditorContent').value='';q('fileEditorSave').textContent='Save file ↗';q('fileEditorHint').textContent=storage==='account'?'A private text document for your account.':'Changes are saved directly to this server’s website. Keep your entry at index.html.';dialog.showModal();opened=true;
  if(file){q('fileEditorSave').disabled=true;try{const data=await api('read',{path:file.path},storage);if(!dialog.open||editor?.path!==file.path||editor?.storage!==storage)return;editor.revision=data.revision||file.revision;const content=data.content;if(typeof content!=='string'){q('fileContentLabel').hidden=true;q('fileEditorHint').textContent='This binary asset is stored on your server. Use Download to save it, or Upload to replace it.';q('fileEditorSave').hidden=true;}else{q('fileEditorContent').value=content;q('fileEditorContent').readOnly=!!file.managed;q('fileEditorSave').hidden=!!file.managed;q('fileEditorSave').disabled=false;if(file.managed)q('fileEditorHint').textContent='Installed app files are read-only here. Manage this app from My tools.';}}catch(e){q('fileEditorStatus').textContent=e.message;}}
  else q('fileEditorName').focus();
 }
 function openMutation(mode,file=null){if(busy)return;resetDialog();editor={mode,path:file?.path||'',revision:file?.revision||null,storage:target()};q('fileContentLabel').hidden=true;q('fileEditorName').value=mode==='mkdir'?(directory?directory+'/':''):file.path;q('fileEditorTitle').textContent=mode==='delete'?'Delete this '+(file.type==='folder'?'folder':'file')+'?':mode==='rename'?'Rename file':'A new folder';q('fileEditorName').readOnly=mode==='delete';q('fileEditorSave').textContent=mode==='delete'?'Delete':mode==='rename'?'Rename ↗':'Create folder ↗';q('fileEditorHint').textContent=mode==='delete'?'This removes '+file.path+' from the selected storage.':mode==='rename'?'Choose a new path. Existing files are kept.':'Use a simple name, or a path such as images/banners.';dialog.showModal();q('fileEditorName').focus();}
 q('fileEditorForm').onsubmit=async e=>{e.preventDefault();if(question){question.resolve(true);question=null;dialog.close();return;}if(busy||!editor)return;const action={...editor},path=q('fileEditorName').value.trim(),content=q('fileEditorContent').value;if(action.mode==='write'&&!action.path&&rows.some(r=>r.path===path)){q('fileEditorStatus').textContent='That file already exists. Open it to edit its contents.';return;}if(action.storage==='account'&&(!/^[A-Za-z0-9][A-Za-z0-9_.-]{0,63}$/.test(path)||path.includes('..'))){q('fileEditorStatus').textContent='Use a simple filename, up to 64 characters.';return;}if(action.storage==='account'&&(!content||content.length>20000)&&action.mode==='write'){q('fileEditorStatus').textContent='Use 1 to 20,000 characters for an account document.';return;}
  busy=true;controls();q('fileEditorSave').disabled=true;q('fileEditorStatus').textContent='Saving…';try{if(action.mode==='write')await api('write',{path,content,base64:encoded(content),revision:action.revision},action.storage);else if(action.mode==='rename')await api('rename',{path:action.path,destination:path,revision:action.revision},action.storage);else await api(action.mode,{path:action.mode==='delete'?action.path:path,revision:action.revision},action.storage);dialog.close();editor=null;await refresh();notice(action.mode==='delete'?'Removed from storage.':action.mode==='rename'?'File renamed.':'Saved to '+(action.storage==='account'?'your private account.':'your server.'));dispatchEvent(new CustomEvent('nuc-server-files-change',{detail:{workspaceId:action.storage}}));}catch(error){q('fileEditorStatus').textContent=error.message;}finally{busy=false;controls();q('fileEditorSave').disabled=false;}};
 async function downloadFile(file){if(busy)return;const storage=target();try{const data=await api('read',{path:file.path},storage);let bytes;if(data.base64){const raw=atob(data.base64);bytes=Uint8Array.from(raw,c=>c.charCodeAt(0));}else bytes=new TextEncoder().encode(data.content);const url=URL.createObjectURL(new Blob([bytes],{type:'application/octet-stream'})),a=el('a');a.href=url;a.download=file.path.split('/').pop();a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notice('Downloaded '+file.path+'.');}catch(e){notice(e.message);}}
 function replaceQuestion(path){resetDialog();editor=null;q('fileNameLabel').hidden=true;q('fileContentLabel').hidden=true;q('fileEditorTitle').textContent='Replace '+path+'?';q('fileEditorHint').textContent='A file with this path already exists. Uploading this file replaces its current contents.';q('fileEditorSave').textContent='Replace file ↗';dialog.showModal();return new Promise(resolve=>question={resolve});}
 async function upload(files){if(busy||!client.state.user)return;const storage=target();for(const file of files){const path=(storage==='account'?'':directory?directory+'/':'')+file.name,existing=rows.find(r=>r.path===path);if(file.size>1048576){notice(file.name+' exceeds the server disk allowance.');break;}if(existing){if(existing.managed){notice('Manage installed app files from My tools.');break;}if(!await replaceQuestion(path))continue;}busy=true;controls();notice('Uploading '+file.name+'…');try{let payload;if(storage==='account'){const content=await file.text();if(!content||content.length>20000||content.includes('\0'))throw Error('Account documents must be text with 1 to 20,000 characters.');payload={path,content};}else{const bytes=new Uint8Array(await file.arrayBuffer());let raw='';for(let i=0;i<bytes.length;i+=8192)raw+=String.fromCharCode(...bytes.subarray(i,i+8192));payload={path,base64:btoa(raw),revision:existing?.revision||null};}await api('write',payload,storage);await refresh();notice('Uploaded '+file.name+'.');dispatchEvent(new CustomEvent('nuc-server-files-change',{detail:{workspaceId:storage}}));}catch(e){notice(e.message);break;}finally{busy=false;controls();}}q('filesUpload').value='';}
 q('filesRefresh').onclick=refresh;q('filesNew').onclick=()=>openEditor();q('filesFolder').onclick=()=>openMutation('mkdir');q('filesUpload').onchange=e=>upload([...e.target.files]);q('filesTarget').onchange=()=>{directory='';refresh();};const drop=q('filesDrop');for(const event of ['dragenter','dragover'])drop.addEventListener(event,e=>{e.preventDefault();drop.classList.add('dragging');});drop.addEventListener('dragleave',()=>drop.classList.remove('dragging'));drop.addEventListener('drop',e=>{e.preventDefault();drop.classList.remove('dragging');upload([...e.dataTransfer.files]);});
 detail.addEventListener('toggle',()=>{if(detail.open&&!opened){opened=true;refresh();}});
 client.ready.then(async()=>{controls();if(client.state.user){try{const data=await client.request('workspaces');workspaces=data.workspaces.filter(w=>w.server&&w.canManageServer);for(const w of workspaces){const o=el('option','',w.project+' · server files');o.value=w.id;q('filesTarget').append(o);}const requested=new URLSearchParams(location.search).get('server')||window.NUC_DEV_RUNTIME?.selected();if(workspaces.some(w=>w.id===requested))q('filesTarget').value=requested;else if(workspaces.length)q('filesTarget').value=workspaces[0].id;}catch(e){notice(e.message);}}await refresh();if(location.hash==='#deskFiles')window.NUC_DEV_PANELS.open('deskFiles');});
 window.NUC_FILES={open:()=>window.NUC_DEV_PANELS.open('deskFiles'),refresh};
})();
