/* Read-only Solana pool data. No keys, signatures, transactions, or invented metrics. */
(() => {
 const root=document.querySelector('[data-live-market]');if(!root||root.dataset.liveMarket==='detail'&&new URLSearchParams(location.search).get('plan')==='local')return;
 const modern=['editorial','workspace'].includes(root.dataset.marketPresentation);
 const API='https://api.dexscreener.com',address=/^[1-9A-HJ-NP-Za-km-z]{32,44}$/;
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const number=v=>v===null||v===undefined||v===''||!Number.isFinite(Number(v))?null:Number(v);
 const usd=v=>number(v)===null?'Unavailable':new Intl.NumberFormat(undefined,{style:'currency',currency:'USD',maximumFractionDigits:Number(v)<1?8:2,notation:Number(v)>=100000?'compact':'standard'}).format(Number(v));
 const change=v=>number(v)===null?'Unavailable':`${Number(v)>0?'+':''}${Number(v).toFixed(2)}%`;
 const stamp=v=>new Date(v).toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit',second:'2-digit'});
 let lastVisible=[],pairs=[],checkedAt=null,controller,requestId=0,launchpad="all",registryData,listed=[],watchView=false,visibleLimit=matchMedia('(max-width:600px)').matches?6:12;
 let saved=[];try{const value=JSON.parse(localStorage.getItem('nucLiveWatchlist')||'[]');if(Array.isArray(value))saved=value.filter(s=>address.test(s.pair)&&address.test(s.token)&&typeof s.name==='string').slice(0,20);}catch{}
 const status=document.querySelector('#marketStatus'),results=document.querySelector('#marketResults');
 function watch(pair){const exists=saved.some(s=>s.pair===pair.pairAddress);const next=exists?saved.filter(s=>s.pair!==pair.pairAddress):[...saved,{pair:pair.pairAddress,token:pair.baseToken.address,name:String(pair.baseToken.name).slice(0,100),symbol:String(pair.baseToken.symbol).slice(0,10),imageUrl:imageUrl(pair)}];if(next.length>20){status.textContent='Your watchlist holds up to 20 pools.';return;}try{localStorage.setItem('nucLiveWatchlist',JSON.stringify(next));saved=next;window.dispatchEvent(new Event('nucLiveWatchChange'));render();if(modern){const target=results.querySelector(`[data-live-watch="${pair.pairAddress}"]`);const watchButton=document.querySelector('[data-market-watchlist]'),fallback=watchButton&&!watchButton.closest('[hidden]')?watchButton:document.querySelector('[data-open-watch]')||document.querySelector('#liveMarketSearch');(target||fallback)?.focus({preventScroll:true});}status.textContent=exists?'Pool removed from your watchlist.':'Pool saved on this device.';}catch{status.textContent='This browser could not save your watchlist.';}}
 function valid(p){return p?.chainId==='solana'&&address.test(p.pairAddress)&&address.test(p.baseToken?.address)&&typeof p.baseToken?.name==='string'&&typeof p.baseToken?.symbol==='string';}
 const imageUrl=p=>{try{const u=new URL(p?.info?.imageUrl||'');return u.protocol==='https:'&&!u.username&&!u.password?u.href:null;}catch{return null;}};
 function tokenArt(p,cls='tile-symbol'){const url=imageUrl(p);return `<span class="${cls} token-profile" aria-hidden="true"><b>${esc(p.baseToken.symbol.slice(0,2))}</b>${url?`<img src="${esc(url)}" alt="" loading="lazy" decoding="async" referrerpolicy="no-referrer" data-token-profile>`:''}</span>`;}
 window.NUC_TOKEN_ART={html:tokenArt,imageUrl};
 document.addEventListener('error',e=>{if(e.target.matches?.('[data-token-profile]'))e.target.hidden=true;},true);
 const metric=(label,value)=>`<div><dt>${label}</dt><dd>${esc(value)}</dd></div>`;
 function workspaceCard(p,on){const token=p.baseToken,delta=number(p.priceChange?.h24);return `<article class="live-pair pool-tile" aria-label="${esc(token.name)} pool"><div class="tile-top">${tokenArt(p)}<div class="tile-identity"><h3 title="${esc(token.name)}">${esc(token.name)}</h3><small>${esc(token.symbol)} / ${esc(p.quoteToken?.symbol||'Unknown')}</small></div><button type="button" data-live-watch="${esc(p.pairAddress)}" aria-pressed="${on}" aria-label="${on?'Unwatch':'Watch'} ${esc(token.name)}">${on?'★':'☆'}</button></div><div class="tile-price"><div><small>PRICE / USD</small><b>${esc(usd(p.priceUsd))}</b></div><span class="tile-change" aria-label="24 hour change ${esc(change(delta))}">${delta===null?'':delta>0?'↗ ':delta<0?'↘ ':''}${esc(change(delta))}</span></div><dl class="live-metrics">${metric('Liquidity',usd(p.liquidity?.usd))}${metric('24h volume',usd(p.volume?.h24))}</dl><div class="tile-origin">${origin(p)||`<span class="tile-venue">${esc(p.dexId)} / SOLANA</span>`}</div><footer><button type="button" data-pool-inspect="${esc(p.pairAddress)}" aria-label="Quick look at ${esc(token.name)}">QUICK LOOK <span aria-hidden="true">↗</span></button><a href="coin.html?pair=${encodeURIComponent(p.pairAddress)}">OPEN POOL ↗</a></footer></article>`;}

 function editorialCard(p,on){const token=p.baseToken,phase=[...token.address].reduce((n,c)=>n+c.charCodeAt(0),0)%31,delta=number(p.priceChange?.h24);return `<article class="live-pair explore-pool" aria-label="${esc(token.name)} pool"><div class="explore-pool-top">${origin(p)||`<span class="explore-venue">${esc(p.dexId)} / SOLANA</span>`}<button type="button" data-live-watch="${esc(p.pairAddress)}" aria-pressed="${on}" aria-label="${on?'Unwatch':'Watch'} ${esc(token.name)}">${on?'SAVED ✓':'SAVE ☆'}</button></div><div class="explore-pool-identity"><div class="explore-token-art" aria-hidden="true"><canvas data-dot-field="bloom" data-dot-phase="${phase}"></canvas><span>${esc(token.symbol.slice(0,3))}</span></div><div class="explore-pool-name"><h3 title="${esc(token.name)}">${esc(token.name)}</h3><small>${esc(token.symbol)} / ${esc(p.quoteToken?.symbol||'Unknown')} · ${esc(p.dexId)}</small></div></div><div class="explore-pool-price"><div><span>OBSERVED PRICE / USD</span><b>${esc(usd(p.priceUsd))}</b></div><span class="explore-pool-change"><small>24H CHANGE</small><span>${delta===null?'':delta>0?'↗ ':delta<0?'↘ ':''}${esc(change(delta))}</span></span></div><dl class="live-metrics">${metric('Liquidity',usd(p.liquidity?.usd))}${metric('24h volume',usd(p.volume?.h24))}</dl><p class="live-address">Mint · ${esc(token.address)}</p><footer><a href="coin.html?pair=${encodeURIComponent(p.pairAddress)}">OPEN POOL ↗</a><a href="https://dexscreener.com/solana/${encodeURIComponent(p.pairAddress)}" target="_blank" rel="noopener noreferrer">DEX SCREENER ↗</a></footer></article>`;}
 function origin(p){const c=registryData?.coins.find(c=>c.mint===p.baseToken.address);return c?`<a class="launch-origin" href="${esc(c.sourceUrl)}" target="_blank" rel="noopener noreferrer">${window.NUC_BRANDS?.logo(c.launchpad)||''}LISTED BY ${esc(NUC_LAUNCHPADS.label(c.launchpad))} ↗</a>`:launchpad==='pump'?'<span class="launch-origin"><img class="service-logo native-logo" src="assets/partners/pump.ico" alt="" aria-hidden="true">PUMP.FUN TRADING VENUE</span>':'';}
 function listing(c){if(modern)return `<article class="launch-listed"><span class="launch-origin">${window.NUC_BRANDS?.logo(c.launchpad)||''}${esc(NUC_LAUNCHPADS.label(c.launchpad))} LISTING</span><h3>${esc(c.name||c.symbol||'New listing')}</h3><p class="explore-listing-note">The listing is available from its source. An indexed market pool wasn’t returned in this observation.</p><span class="explore-listing-state">MARKET DATA / UNAVAILABLE</span><p class="live-address">Mint · ${esc(c.mint)}</p><footer><a href="${esc(c.sourceUrl)}" target="_blank" rel="noopener noreferrer">OPEN LISTING ↗</a><a href="https://solscan.io/token/${encodeURIComponent(c.mint)}" target="_blank" rel="noopener noreferrer">SOLSCAN ↗</a></footer></article>`;return `<article class="launch-listed"><span class="launch-origin">${window.NUC_BRANDS?.logo(c.launchpad)||''}LISTED BY ${esc(NUC_LAUNCHPADS.label(c.launchpad))}</span><h3>${esc(c.name||c.symbol||'New listing')}</h3><p>Market data unavailable. No indexed pool was returned in this observation.</p><p class="live-address">${esc(c.mint)}</p><footer><a href="${esc(c.sourceUrl)}" target="_blank" rel="noopener noreferrer">OFFICIAL LISTING ↗</a><a href="https://solscan.io/token/${encodeURIComponent(c.mint)}" target="_blank" rel="noopener noreferrer">SOLSCAN ↗</a></footer></article>`;}
 function classicCard(p,on,featured){const token=p.baseToken,phase=[...token.address].reduce((n,c)=>n+c.charCodeAt(0),0)%31;return `<article class="live-pair coin-card${featured?' featured':''}" aria-label="${esc(token.name)} pool"><div class="coin-card-head live-pair-head"><div class="coin-id"><div class="coin-avatar live-token-avatar" aria-hidden="true">${esc(token.symbol.slice(0,3))}</div><div><h3 title="${esc(token.name)}">${esc(token.name)}</h3><small>${esc(token.symbol)} / ${esc(p.quoteToken?.symbol||'Unknown')}</small></div></div><button type="button" data-live-watch="${esc(p.pairAddress)}" aria-pressed="${on}" aria-label="${on?'Unwatch':'Watch'} ${esc(token.name)}">${on?'SAVED ✓':'SAVE ☆'}</button></div><div class="coin-art-wrap"><canvas class="coin-art" data-dot-field="bloom" data-dot-phase="${phase}" aria-hidden="true"></canvas><div class="coin-identity-mark" aria-hidden="true">${esc(token.symbol.slice(0,4))}</div><span class="coin-art-caption">SOLANA / ${esc(p.dexId)}</span><span class="coin-observed-price"><small>OBSERVED PRICE</small><b>${esc(usd(p.priceUsd))}</b></span></div><dl class="coin-card-meta live-metrics">${metric('24h change',change(p.priceChange?.h24))}${metric('Liquidity',usd(p.liquidity?.usd))}${metric('24h volume',usd(p.volume?.h24))}</dl><div class="coin-card-source">${origin(p)}</div><p class="live-address">Mint · ${esc(token.address)}</p><footer><a href="coin.html?pair=${encodeURIComponent(p.pairAddress)}">INSPECT POOL ↗</a><a href="https://dexscreener.com/solana/${encodeURIComponent(p.pairAddress)}" target="_blank" rel="noopener noreferrer">DEX SCREENER ↗</a></footer></article>`;}
 function releaseArt(){results.querySelectorAll('[data-dot-field]').forEach(c=>window.NUC_DOTS?.unmount?.(c));}
 function overview(visible,missing){if(!['classic','editorial','workspace'].includes(root.dataset.marketPresentation))return;const set=(selector,value)=>document.querySelectorAll(selector).forEach(e=>e.textContent=value),top=[...visible].sort((a,b)=>(number(b.volume?.h24)??-1)-(number(a.volume?.h24)??-1))[0];set('[data-explore-indexed]',visible.length);set('[data-explore-saved]',saved.length);set('[data-explore-listed]',visible.length+missing.length);set('[data-explore-top-volume]',top?usd(top.volume?.h24):'—');set('[data-explore-top-name]',top?top.baseToken.name:'No matching observation');const queue=document.querySelector('#explorePoolQueue');if(queue)queue.innerHTML=visible.slice(0,4).map(p=>`<a class="queue-row" href="coin.html?pair=${encodeURIComponent(p.pairAddress)}"><span>${esc(p.baseToken.symbol)}</span><b>${esc(p.dexId)}</b><em>${esc(usd(p.liquidity?.usd))} LIQ</em></a>`).join('')||'<p class="queue-empty">No indexed pools in this view.</p>';}
 function card(p,featured=false){const on=saved.some(s=>s.pair===p.pairAddress);if(root.dataset.marketPresentation==='workspace')return workspaceCard(p,on);if(modern)return editorialCard(p,on);if(root.dataset.marketPresentation==='classic')return classicCard(p,on,featured);return `<article class="live-pair"><div class="live-pair-head"><div><small>${esc(p.dexId)} · SOLANA</small><h3>${esc(p.baseToken.name)}</h3><small>${esc(p.baseToken.symbol)} / ${esc(p.quoteToken?.symbol||'Unknown')}</small></div><button type="button" data-live-watch="${esc(p.pairAddress)}" aria-pressed="${on}" aria-label="${on?'Unwatch':'Watch'} ${esc(p.baseToken.name)}">${on?'SAVED ✓':'SAVE ☆'}</button></div>${origin(p)}<dl class="live-metrics">${metric('Price',usd(p.priceUsd))}${metric('24h change',change(p.priceChange?.h24))}${metric('Liquidity',usd(p.liquidity?.usd))}${metric('24h volume',usd(p.volume?.h24))}</dl><p class="live-address">Token · ${esc(p.baseToken.address)}</p><footer><a href="coin.html?pair=${encodeURIComponent(p.pairAddress)}">INSPECT POOL ↗</a><a href="https://dexscreener.com/solana/${encodeURIComponent(p.pairAddress)}" target="_blank" rel="noopener noreferrer">DEX SCREENER ↗</a></footer></article>`;}
 function publish(){if(!modern)return;const detail={state:root.dataset.marketState||'loading',visiblePairs:[...lastVisible],allPairs:[...pairs],saved:saved.map(s=>({...s})),checkedAt};window.dispatchEvent(new CustomEvent('nuc:market-update',{detail}));}
 if(modern)window.NUC_MARKET={getState:()=>({state:root.dataset.marketState||'loading',visiblePairs:[...lastVisible],allPairs:[...pairs],saved:saved.map(s=>({...s})),checkedAt}),toggleSaved(pair){const record=pairs.find(p=>p.pairAddress===pair);if(record)watch(record);},removeSaved(pair){if(saved.some(s=>s.pair===pair))watch({pairAddress:pair});}};
 function render(){
  if(root.dataset.liveMarket==='detail'){renderDetail();return;}
  const sort=document.querySelector('#marketSort').value,watchOnly=document.querySelector('#marketWatchOnly').checked;
  const q=document.querySelector('#liveMarketSearch').value.trim().toLowerCase();const match=p=>!q||`${p.baseToken.name} ${p.baseToken.symbol} ${p.baseToken.address}`.toLowerCase().includes(q);const visible=pairs.filter(p=>((watchView&&!modern)||match(p))&&(!watchOnly||saved.some(s=>s.pair===p.pairAddress))).sort((a,b)=>(number(sort==='volume'?b.volume?.h24:sort==='change'?b.priceChange?.h24:sort==='newest'?b.pairCreatedAt:b.liquidity?.usd)??-Infinity)-(number(sort==='volume'?a.volume?.h24:sort==='change'?a.priceChange?.h24:sort==='newest'?a.pairCreatedAt:a.liquidity?.usd)??-Infinity));
  const missing=watchOnly||watchView?[]:listed.filter(c=>!q||`${c.name||''} ${c.symbol||''} ${c.mint}`.toLowerCase().includes(q));lastVisible=visible;overview(visible,missing);const markup=[...visible.map((p,index)=>card(p,index===0)),...missing.map(listing)],classic=['classic','editorial','workspace'].includes(root.dataset.marketPresentation),shown=classic?markup.slice(0,visibleLimit):markup;releaseArt();const empty=modern?`<div class="working-empty"><h3>${(watchOnly||watchView)&&!saved.length?'Your shelf is waiting.':'Nothing in this view yet.'}</h3><p>${(watchOnly||watchView)&&!saved.length?'Save a pool from the collection to keep it here. Your watchlist stays on this device.':'Try another name or mint address, or reset the source and watchlist filters.'}</p><button type="button" data-explore-reset-filters>BROWSE ALL SOURCES ↗</button></div>`:null;results.innerHTML=shown.join('')||empty||'<div class="working-empty">No pools match this view. Try another name or token address, or turn off the watchlist filter.</div>';results.querySelectorAll('[data-dot-field]').forEach(c=>window.NUC_DOTS?.mount(c));const more=document.querySelector('#marketMore');if(more){more.hidden=markup.length<=visibleLimit;more.textContent=`${modern?'LOAD MORE OBSERVATIONS':'SHOW MORE LAUNCHES'} / ${Math.max(0,markup.length-visibleLimit)} REMAINING ↓`;}
  document.querySelector('#marketCount').textContent=`${classic?`Showing ${Math.min(visibleLimit,markup.length)} of ${markup.length} listings · `:''}${visible.length} Solana pools · ${missing.length} listings without indexed pools · ${saved.length} saved on this device`;publish();
 }
 function renderDetail(){const p=pairs[0];if(!p){results.innerHTML='<div class="working-empty">No indexed Solana pool was returned for this address.</div>';return;}document.title=`NUCALORIC — ${p.baseToken.name}`;if(window.NUC_PORTFOLIO){window.NUC_PORTFOLIO.renderPool(p,checkedAt,saved);results.innerHTML='';return;}
  results.innerHTML=`<div class="market-detail"><span class="kicker">${esc(p.dexId)} / SOLANA / PUBLIC POOL OBSERVATION</span><h1>${esc(p.baseToken.name)}</h1><p>${esc(p.baseToken.symbol)} / ${esc(p.quoteToken?.symbol||'Unknown')}</p>${card(p)}<dl class="live-metrics">${metric('Market cap',usd(p.marketCap))}${metric('Fully diluted valuation',usd(p.fdv))}${metric('24h buys',number(p.txns?.h24?.buys)===null?'Unavailable':Number(p.txns.h24.buys).toLocaleString())}${metric('24h sells',number(p.txns?.h24?.sells)===null?'Unavailable':Number(p.txns.h24.sells).toLocaleString())}${metric('Pool created',Number.isFinite(p.pairCreatedAt)?new Date(p.pairCreatedAt).toLocaleDateString():'Unavailable')}</dl><p class="live-address">Pool · ${esc(p.pairAddress)}</p><p>These are provider-reported pool observations. Holder counts, ownership, liquidity locks, token safety and AI scores are not established by this feed.</p><a href="https://solscan.io/token/${encodeURIComponent(p.baseToken.address)}" target="_blank" rel="noopener noreferrer">INSPECT TOKEN ON SOLSCAN ↗</a></div>`;
 }
 async function load(query,watchlist=false){
  controller?.abort();controller=new AbortController();const currentController=controller,id=++requestId;checkedAt=null;if(root.dataset.liveMarket==='detail'){const profile=document.querySelector('#portfolioWorkspace');if(profile)profile.hidden=true;}lastVisible=[];pairs=[];listed=[];visibleLimit=matchMedia('(max-width:600px)').matches?6:12;watchView=watchlist;releaseArt();results.innerHTML='';if(modern){root.dataset.marketState='loading';results.setAttribute('aria-busy','true');results.innerHTML='<div class="explore-skeleton" aria-hidden="true"><i></i><i></i><i></i><i></i></div>'.repeat(3);}overview([],[]);if(modern)document.querySelectorAll('[data-explore-indexed]').forEach(e=>e.textContent='—');if(document.querySelector('#marketMore'))document.querySelector('#marketMore').hidden=true;if(document.querySelector('#marketCount'))document.querySelector('#marketCount').textContent='Awaiting current observations';status.textContent='Reading public Solana pools…';document.querySelectorAll('[data-market-refresh]').forEach(b=>b.disabled=true);
  publish();const timer=setTimeout(()=>currentController.abort(),30000);
  try{
   let url;if(root.dataset.liveMarket==='explore'&&!watchlist&&!(launchpad==='all'&&query.trim())){
    registryData=await NUC_LAUNCHPADS.registry(currentController.signal);if(id!==requestId)return;
    const evidence=document.querySelector('#launchpadEvidence');evidence.textContent=`OTC registry: ${registryData.otcLive?'read live':'saved catalog — live registry unavailable'}. PAID registry: verified catalog from ${new Date(registryData.checkedAt).toLocaleString()}; browser access to its live registry is unavailable. Pool prices are requested separately on each refresh.`;
    let records;
    if(launchpad==='pump'){const r=await fetch(`${API}/latest/dex/search?q=${encodeURIComponent(query.trim()||'pump')}`,{signal:currentController.signal});if(!r.ok)throw Error('The market provider could not be read.');const d=await r.json();if(!Array.isArray(d.pairs))throw Error('Invalid pool response.');records=d.pairs.filter(p=>['pumpfun','pumpswap'].includes(p.dexId));evidence.textContent='This view identifies Pump.fun / PumpSwap trading venues. It does not prove the original launchpad or creator. Refresh requests current pool observations.';}
    else{const coins=registryData.coins.filter(c=>launchpad==='all'||c.launchpad===launchpad).slice(0,60);const batches=[];for(let i=0;i<coins.length;i+=30)batches.push(coins.slice(i,i+30));const groups=await Promise.all(batches.map(async group=>{const r=await fetch(`${API}/tokens/v1/solana/${group.map(c=>c.mint).join(',')}`,{signal:currentController.signal});if(!r.ok)throw Error(r.status===429?'The provider rate limit was reached. Try again shortly.':'The market provider is unavailable. Try again.');const d=await r.json();if(!Array.isArray(d))throw Error('Invalid pool response.');return d;}));records=groups.flat().filter(p=>coins.some(c=>c.mint===p.baseToken?.address));listed=coins.filter(c=>!records.some(p=>valid(p)&&p.baseToken.address===c.mint));}
    if(id!==requestId)return;const best=new Map();records.filter(valid).forEach(p=>{const previous=best.get(p.baseToken.address);if(!previous||(number(p.liquidity?.usd)??-1)>(number(previous.liquidity?.usd)??-1))best.set(p.baseToken.address,p);});pairs=[...best.values()];checkedAt=Date.now();render();status.textContent=`Pool observations received at ${stamp(checkedAt)}. Listings are source-attributed; refresh for new market data.`;return;
   }
   if(watchlist){if(!saved.length){status.textContent='Your watchlist is empty. Save a pool from the search results.';render();return;}url=`${API}/latest/dex/pairs/solana/${saved.map(s=>s.pair).join(',')}`;}else if(root.dataset.liveMarket==='detail'){if(!address.test(query))throw Error('Choose a live pool from Explore.');url=`${API}/latest/dex/pairs/solana/${encodeURIComponent(query)}`;}else{if(!query.trim()||query.length>120)throw Error('Enter a name, symbol, or Solana address (up to 120 characters).');url=address.test(query.trim())?`${API}/token-pairs/v1/solana/${encodeURIComponent(query.trim())}`:`${API}/latest/dex/search?q=${encodeURIComponent(query.trim())}`;}
   const response=await fetch(url,{headers:{Accept:'application/json'},signal:currentController.signal});if(!response.ok)throw Error(response.status===429?'The provider rate limit was reached. Try again shortly.':'The market provider is unavailable. Try again.');
   const data=await response.json(),records=Array.isArray(data)?data:data.pairs;if(!Array.isArray(records))throw Error('The provider returned an unreadable response.');if(id!==requestId)return;
   const unique=new Map(records.filter(p=>valid(p)&&(root.dataset.liveMarket!=='detail'||p.pairAddress===query)).map(p=>[p.pairAddress,p]));pairs=[...unique.values()].slice(0,30);checkedAt=Date.now();render();status.textContent=`Provider response received at ${stamp(checkedAt)}. Refresh for a new observation.`;
  }catch(error){if(id!==requestId)return;if(modern)root.dataset.marketState='error';status.textContent=error.name==='AbortError'?'The market request timed out. Try again.':error.message;releaseArt();overview([],[]);if(modern){document.querySelectorAll('[data-explore-indexed]').forEach(e=>e.textContent='—');document.querySelector('#marketCount').textContent='Observation unavailable';results.innerHTML='<div class="market-error"><h3>A pause in the feed.</h3><p>Current pool observations could not be read. Refresh to try again.</p><button type="button" data-explore-retry>TRY THE FEED AGAIN ↻</button></div>';}else results.innerHTML='<div class="market-error">Current market data is unavailable. No example prices are substituted. <a href="explorer.html">RETURN TO EXPLORE ↗</a></div>';}
  finally{clearTimeout(timer);if(id===requestId){if(modern){results.setAttribute('aria-busy','false');if(root.dataset.marketState!=='error')root.dataset.marketState='ready';}document.querySelectorAll('[data-market-refresh]').forEach(b=>b.disabled=false);publish();}}
 }
 root.addEventListener('click',event=>{const button=event.target.closest('[data-live-watch]');if(button){const pair=pairs.find(p=>p.pairAddress===button.dataset.liveWatch);if(pair)watch(pair);}});
 if(root.dataset.liveMarket==='detail'){load(new URLSearchParams(location.search).get('pair')||'');document.querySelector('[data-market-refresh]').addEventListener('click',()=>load(new URLSearchParams(location.search).get('pair')||''));}
 else{const search=document.querySelector('#liveMarketSearch');document.querySelector('[data-market-refresh][type="button"]')?.addEventListener('click',()=>load(search.value,document.querySelector('#marketWatchOnly').checked));document.querySelector('#liveMarketForm').addEventListener('submit',e=>{e.preventDefault();document.querySelector('#marketWatchOnly').checked=false;load(search.value);});search.addEventListener('input',()=>{visibleLimit=matchMedia('(max-width:600px)').matches?6:12;if(launchpad!=='pump'||(watchView&&modern))render();});document.querySelector('#marketSort').addEventListener('change',render);document.querySelector('#marketWatchOnly').addEventListener('change',render);document.querySelectorAll('[data-launchpad]').forEach(b=>b.addEventListener('click',()=>{launchpad=b.dataset.launchpad;search.value='';document.querySelector('#marketWatchOnly').checked=false;document.querySelectorAll('[data-launchpad]').forEach(x=>{x.setAttribute('aria-pressed',String(x===b));x.classList.toggle('active',x===b);});load('');}));document.querySelector('[data-market-watchlist]').addEventListener('click',()=>{search.value='';document.querySelector('#marketWatchOnly').checked=true;load('',true);});load(search.value);}

 document.querySelector('#marketMore')?.addEventListener('click',()=>{visibleLimit+=matchMedia('(max-width:600px)').matches?6:12;render();if(document.querySelector('#marketMore').hidden)results.querySelector('article:last-child a')?.focus({preventScroll:true});});
 setInterval(()=>{if(checkedAt&&Date.now()-checkedAt>60000)status.textContent=`Last observation ${stamp(checkedAt)}. These prices may have changed; refresh for current data.`;},15000);
})();
