/* Read-only Solana pool data. No keys, signatures, transactions, or invented metrics. */
(() => {
 const root=document.querySelector('[data-live-market]');if(!root)return;
 const API='https://api.dexscreener.com',address=/^[1-9A-HJ-NP-Za-km-z]{32,44}$/;
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const number=v=>v===null||v===undefined||v===''||!Number.isFinite(Number(v))?null:Number(v);
 const usd=v=>number(v)===null?'Unavailable':new Intl.NumberFormat(undefined,{style:'currency',currency:'USD',maximumFractionDigits:Number(v)<1?8:2,notation:Number(v)>=100000?'compact':'standard'}).format(Number(v));
 const change=v=>number(v)===null?'Unavailable':`${Number(v)>0?'+':''}${Number(v).toFixed(2)}%`;
 const stamp=v=>new Date(v).toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit',second:'2-digit'});
 let pairs=[],checkedAt=null,controller,requestId=0;
 let saved=[];try{const value=JSON.parse(localStorage.getItem('nucLiveWatchlist')||'[]');if(Array.isArray(value))saved=value.filter(s=>address.test(s.pair)&&address.test(s.token)&&typeof s.name==='string').slice(0,20);}catch{}
 const status=document.querySelector('#marketStatus'),results=document.querySelector('#marketResults');
 function watch(pair){const exists=saved.some(s=>s.pair===pair.pairAddress);const next=exists?saved.filter(s=>s.pair!==pair.pairAddress):[...saved,{pair:pair.pairAddress,token:pair.baseToken.address,name:String(pair.baseToken.name).slice(0,100)}];if(next.length>20){status.textContent='Your watchlist holds up to 20 pools.';return;}try{localStorage.setItem('nucLiveWatchlist',JSON.stringify(next));saved=next;window.dispatchEvent(new Event('nucLiveWatchChange'));render();status.textContent=exists?'Pool removed from your watchlist.':'Pool saved on this device.';}catch{status.textContent='This browser could not save your watchlist.';}}
 function valid(p){return p?.chainId==='solana'&&address.test(p.pairAddress)&&address.test(p.baseToken?.address)&&typeof p.baseToken?.name==='string'&&typeof p.baseToken?.symbol==='string';}
 const metric=(label,value)=>`<div><dt>${label}</dt><dd>${esc(value)}</dd></div>`;
 function card(p){const on=saved.some(s=>s.pair===p.pairAddress);return `<article class="live-pair"><div class="live-pair-head"><div><small>${esc(p.dexId)} · SOLANA</small><h3>${esc(p.baseToken.name)}</h3><small>${esc(p.baseToken.symbol)} / ${esc(p.quoteToken?.symbol||'Unknown')}</small></div><button type="button" data-live-watch="${esc(p.pairAddress)}" aria-pressed="${on}" aria-label="${on?'Unwatch':'Watch'} ${esc(p.baseToken.name)}">${on?'SAVED ✓':'SAVE ☆'}</button></div><dl class="live-metrics">${metric('Price',usd(p.priceUsd))}${metric('24h change',change(p.priceChange?.h24))}${metric('Liquidity',usd(p.liquidity?.usd))}${metric('24h volume',usd(p.volume?.h24))}</dl><p class="live-address">Token · ${esc(p.baseToken.address)}</p><footer><a href="coin.html?pair=${encodeURIComponent(p.pairAddress)}">INSPECT POOL ↗</a><a href="https://dexscreener.com/solana/${encodeURIComponent(p.pairAddress)}" target="_blank" rel="noopener noreferrer">DEX SCREENER ↗</a></footer></article>`;}
 function render(){
  if(root.dataset.liveMarket==='detail'){renderDetail();return;}
  const sort=document.querySelector('#marketSort').value,watchOnly=document.querySelector('#marketWatchOnly').checked;
  const visible=pairs.filter(p=>!watchOnly||saved.some(s=>s.pair===p.pairAddress)).sort((a,b)=>(number(sort==='volume'?b.volume?.h24:sort==='change'?b.priceChange?.h24:b.liquidity?.usd)??-Infinity)-(number(sort==='volume'?a.volume?.h24:sort==='change'?a.priceChange?.h24:a.liquidity?.usd)??-Infinity));
  results.innerHTML=visible.map(card).join('')||'<div class="working-empty">No pools match this view. Try another name or token address, or turn off the watchlist filter.</div>';
  document.querySelector('#marketCount').textContent=`${visible.length} Solana pools · ${saved.length} saved on this device`;
 }
 function renderDetail(){const p=pairs[0];if(!p){results.innerHTML='<div class="working-empty">No indexed Solana pool was returned for this address.</div>';return;}document.title=`NUCALORIC — ${p.baseToken.name}`;
  results.innerHTML=`<div class="market-detail"><span class="kicker">${esc(p.dexId)} / SOLANA / PUBLIC POOL OBSERVATION</span><h1>${esc(p.baseToken.name)}</h1><p>${esc(p.baseToken.symbol)} / ${esc(p.quoteToken?.symbol||'Unknown')}</p>${card(p)}<dl class="live-metrics">${metric('Market cap',usd(p.marketCap))}${metric('Fully diluted valuation',usd(p.fdv))}${metric('24h buys',number(p.txns?.h24?.buys)===null?'Unavailable':Number(p.txns.h24.buys).toLocaleString())}${metric('24h sells',number(p.txns?.h24?.sells)===null?'Unavailable':Number(p.txns.h24.sells).toLocaleString())}${metric('Pool created',Number.isFinite(p.pairCreatedAt)?new Date(p.pairCreatedAt).toLocaleDateString():'Unavailable')}</dl><p class="live-address">Pool · ${esc(p.pairAddress)}</p><p>These are provider-reported pool observations. Holder counts, ownership, liquidity locks, token safety and AI scores are not established by this feed.</p><a href="https://solscan.io/token/${encodeURIComponent(p.baseToken.address)}" target="_blank" rel="noopener noreferrer">INSPECT TOKEN ON SOLSCAN ↗</a></div>`;
 }
 async function load(query,watchlist=false){
  controller?.abort();controller=new AbortController();const currentController=controller,id=++requestId;checkedAt=null;pairs=[];results.innerHTML='';status.textContent='Reading public Solana pools…';document.querySelectorAll('[data-market-refresh]').forEach(b=>b.disabled=true);
  const timer=setTimeout(()=>currentController.abort(),12000);
  try{
   let url;if(watchlist){if(!saved.length){status.textContent='Your watchlist is empty. Save a pool from the search results.';render();return;}url=`${API}/latest/dex/pairs/solana/${saved.map(s=>s.pair).join(',')}`;}else if(root.dataset.liveMarket==='detail'){if(!address.test(query))throw Error('Choose a live pool from Explore.');url=`${API}/latest/dex/pairs/solana/${encodeURIComponent(query)}`;}else{if(!query.trim()||query.length>120)throw Error('Enter a name, symbol, or Solana address (up to 120 characters).');url=address.test(query.trim())?`${API}/token-pairs/v1/solana/${encodeURIComponent(query.trim())}`:`${API}/latest/dex/search?q=${encodeURIComponent(query.trim())}`;}
   const response=await fetch(url,{headers:{Accept:'application/json'},signal:currentController.signal});if(!response.ok)throw Error(response.status===429?'The provider rate limit was reached. Try again shortly.':'The market provider is unavailable. Try again.');
   const data=await response.json(),records=Array.isArray(data)?data:data.pairs;if(!Array.isArray(records))throw Error('The provider returned an unreadable response.');if(id!==requestId)return;
   const unique=new Map(records.filter(p=>valid(p)&&(root.dataset.liveMarket!=='detail'||p.pairAddress===query)).map(p=>[p.pairAddress,p]));pairs=[...unique.values()].slice(0,30);checkedAt=Date.now();render();status.textContent=`Provider response received at ${stamp(checkedAt)}. Refresh for a new observation.`;
  }catch(error){if(id!==requestId)return;status.textContent=error.name==='AbortError'?'The market request timed out. Try again.':error.message;results.innerHTML='<div class="market-error">Current market data is unavailable. No example prices are substituted. <a href="explorer.html">RETURN TO EXPLORE ↗</a></div>';}
  finally{clearTimeout(timer);if(id===requestId)document.querySelectorAll('[data-market-refresh]').forEach(b=>b.disabled=false);}
 }
 results.addEventListener('click',event=>{const button=event.target.closest('[data-live-watch]');if(button){const pair=pairs.find(p=>p.pairAddress===button.dataset.liveWatch);if(pair)watch(pair);}});
 if(root.dataset.liveMarket==='detail'){load(new URLSearchParams(location.search).get('pair')||'');document.querySelector('[data-market-refresh]').addEventListener('click',()=>load(new URLSearchParams(location.search).get('pair')||''));}
 else{const search=document.querySelector('#liveMarketSearch');document.querySelector('#liveMarketForm').addEventListener('submit',e=>{e.preventDefault();document.querySelector('#marketWatchOnly').checked=false;load(search.value);});document.querySelector('#marketSort').addEventListener('change',render);document.querySelector('#marketWatchOnly').addEventListener('change',render);document.querySelectorAll('[data-market-query]').forEach(b=>b.addEventListener('click',()=>{search.value=b.dataset.marketQuery;document.querySelector('#marketWatchOnly').checked=false;load(search.value);}));document.querySelector('[data-market-watchlist]').addEventListener('click',()=>{document.querySelector('#marketWatchOnly').checked=true;load('',true);});load(search.value);}
 setInterval(()=>{if(checkedAt&&Date.now()-checkedAt>60000)status.textContent=`Last observation ${stamp(checkedAt)}. These prices may have changed; refresh for current data.`;},15000);
})();
