/* Local workspace preferences, reference-derived matrix labels and native scroll staging. */
(() => {
 const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}};
 const write=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value));return true;}catch{return false;}};
 const modes=['create','build','discover'],raw=read('nucWorkspacePrefs',{});
 let prefs={name:typeof raw.name==='string'?raw.name.slice(0,32):'',mode:modes.includes(raw.mode)?raw.mode:'create',spacing:raw.spacing==='compact'?'compact':'roomy',pins:Array.isArray(raw.pins)?[...new Set(raw.pins.filter(x=>modes.includes(x)))]:[]};
 const dialog=document.querySelector('#workspaceSettings'),nameInput=document.querySelector('#workspaceNickname');
 function apply(){document.body.dataset.workspaceFocus=prefs.mode;document.body.dataset.moduleSpacing=prefs.spacing;document.querySelectorAll('[data-space-name]').forEach(e=>e.textContent=prefs.name||'YOUR SPACE');document.querySelectorAll('[data-workspace-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.workspaceMode===prefs.mode)));const grid=document.querySelector('[data-personal-modules]');if(grid){const nodes=[...grid.children];const rank=id=>prefs.pins.includes(id)?prefs.pins.indexOf(id):id===prefs.mode?5:10+modes.indexOf(id);nodes.sort((a,b)=>rank(a.dataset.homeModule)-rank(b.dataset.homeModule)).forEach(n=>{n.dataset.pinned=String(prefs.pins.includes(n.dataset.homeModule));const b=n.querySelector('[data-pin-module]');b.setAttribute('aria-pressed',n.dataset.pinned);b.textContent=n.dataset.pinned==='true'?'PINNED ✓':'PIN ＋';grid.append(n);});}personalize();}
 function notify(text){if(typeof showToast==='function')showToast(text);}
 document.querySelector('[data-open-workspace]')?.addEventListener('click',()=>{nameInput.value=prefs.name;document.querySelector('#workspaceSpacing').value=prefs.spacing;document.querySelector('#workspacePreferenceStatus').textContent='';dialog.showModal();});document.querySelector('[data-close-workspace]')?.addEventListener('click',()=>dialog.close());
 document.querySelector('[data-save-workspace]')?.addEventListener('click',()=>{prefs={...prefs,name:nameInput.value.trim().slice(0,32),spacing:document.querySelector('#workspaceSpacing').value};const persisted=write('nucWorkspacePrefs',prefs);apply();if(persisted){dialog.close();notify('Your workspace preferences are saved on this device.');}else document.querySelector('#workspacePreferenceStatus').textContent='Browser storage is unavailable. Preferences apply to this page only.';});
 document.querySelectorAll('[data-workspace-mode]').forEach(b=>b.addEventListener('click',()=>{prefs.mode=b.dataset.workspaceMode;const ok=write('nucWorkspacePrefs',prefs);apply();b.focus();notify(ok?'Workspace focus saved. Your homepage modules follow this choice.':'Focus changed for this page. Browser storage is unavailable.');}));
 document.querySelectorAll('[data-pin-module]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.pinModule;prefs.pins=prefs.pins.includes(id)?prefs.pins.filter(x=>x!==id):[...prefs.pins,id];const ok=write('nucWorkspacePrefs',prefs);apply();b.focus();notify(ok?'Module order saved on this device.':'Module order changed for this page only.');}));
 function segments(el,ratio=.55){if(!el)return;el.replaceChildren();for(let i=0;i<36;i++){const bit=document.createElement('i');bit.classList.toggle('is-filled',i<Math.round(Math.max(0,Math.min(1,ratio))*36));el.append(bit);}}
 document.querySelectorAll('.scene-segments').forEach(e=>segments(e,0));
 const glyphs={A:'01110/10001/10001/11111/10001/10001/10001',B:'11110/10001/10001/11110/10001/10001/11110',C:'01111/10000/10000/10000/10000/10000/01111',D:'11110/10001/10001/10001/10001/10001/11110',E:'11111/10000/10000/11110/10000/10000/11111',F:'11111/10000/10000/11110/10000/10000/10000',G:'01111/10000/10000/10111/10001/10001/01111',H:'10001/10001/10001/11111/10001/10001/10001',I:'11111/00100/00100/00100/00100/00100/11111',J:'00111/00010/00010/00010/10010/10010/01100',K:'10001/10010/10100/11000/10100/10010/10001',L:'10000/10000/10000/10000/10000/10000/11111',M:'10001/11011/10101/10101/10001/10001/10001',N:'10001/11001/11001/10101/10011/10011/10001',O:'01110/10001/10001/10001/10001/10001/01110',P:'11110/10001/10001/11110/10000/10000/10000',Q:'01110/10001/10001/10001/10101/10010/01101',R:'11110/10001/10001/11110/10100/10010/10001',S:'01111/10000/10000/01110/00001/00001/11110',T:'11111/00100/00100/00100/00100/00100/00100',U:'10001/10001/10001/10001/10001/10001/01110',V:'10001/10001/10001/10001/10001/01010/00100',W:'10001/10001/10001/10101/10101/11011/10001',X:'10001/10001/01010/00100/01010/10001/10001',Y:'10001/10001/01010/00100/00100/00100/00100',Z:'11111/00001/00010/00100/01000/10000/11111',' ':'00000/00000/00000/00000/00000/00000/00000'};
 function matrix(canvas){const label=String(canvas.dataset.matrixType||'').toUpperCase().slice(0,30),unit=4,w=Math.max(1,label.length*6*unit-unit),h=7*unit,d=Math.min(devicePixelRatio||1,1.5);canvas.width=w*d;canvas.height=h*d;canvas.style.setProperty('--matrix-width',w+'px');const ctx=canvas.getContext('2d');ctx.scale(d,d);ctx.fillStyle='#ffffff';[...label].forEach((char,i)=>(glyphs[char]||glyphs[' ']).split('/').forEach((row,y)=>[...row].forEach((v,x)=>{if(v==='1')ctx.fillRect(i*6*unit+x*unit,y*unit,unit*.62,unit*.62);})));}
 document.querySelectorAll('[data-matrix-type]').forEach(matrix);
 function personalize(){const library=read('nucProjectLibrary',{}),project=Array.isArray(library.projects)?library.projects.find(p=>p?.id===library.activeId):null,coin=read('nucCoinWorkbench',null),watched=read('nucLiveWatchlist',[]),tools=read('nucCapabilityShortlist',[]);let title='Every idea starts somewhere.',caption='Choose a module below and give the idea a first shape.',action='OPEN COIN DESK ↗',href='launchpad.html',progress=0;
  if(prefs.mode==='build'&&project?.draft?.fields){title=String(project.draft.fields.name||'Your next project');const tasks=Array.isArray(project.tasks)?project.tasks:[],done=tasks.filter(t=>t?.done===true).length;caption=`${done} of ${tasks.length} saved milestones complete. Your work stays on this device.`;progress=tasks.length?done/tasks.length:0;action='CONTINUE YOUR PROJECT ↗';href='studio.html?project='+encodeURIComponent(project.id)+'#brief';}
  else if(prefs.mode==='discover'){const count=Array.isArray(watched)?watched.length:0;title=count?`${count} pools on your radar.`:'Follow your curiosity.';caption='Your saved pools, with a fresh observation when you request one.';action='OPEN YOUR MARKET WATCH ↗';href='explorer.html';}
  else if(coin?.version===1&&coin.fields){title=String(coin.fields.name||'Your coin is taking shape.');const filled=['name','ticker','story'].filter(k=>typeof coin.fields[k]==='string'&&coin.fields[k].trim()).length;caption=`${filled} of 3 identity details added. Launch plan saved locally.`;progress=filled/3;action='CONTINUE YOUR COIN PLAN ↗';}
  const set=(selector,text)=>{const e=document.querySelector(selector);if(e)e.textContent=text;};set('[data-personal-title]',title);set('[data-personal-caption]',caption);const link=document.querySelector('[data-personal-action]');if(link){link.textContent=action;link.href=href;}segments(document.querySelector('[data-personal-meter]'),progress);set('[data-personal-tools]',Array.isArray(tools)?tools.length:0);
  if(coin?.version===1&&coin.fields?.name)set('[data-module-create]',`${String(coin.fields.name)} · your saved coin plan. Continue shaping its identity, budget and distribution.`);
  if(project?.draft?.fields?.name)set('[data-module-build]',`${String(project.draft.fields.name)} · your active project. Pick up your next milestone in Studio.`);
  if(Array.isArray(watched)&&watched.length)set('[data-module-discover]',`${watched.length} saved pools on this device. Request fresh observations in Explore.`);
 }
 const reduced=matchMedia('(prefers-reduced-motion:reduce)'),buttons=[...document.querySelectorAll('[data-modular-motion]')];
 function motion(){const paused=window.NUC_DOTS?.isPaused()||false;document.body.classList.toggle('motion-paused',paused);buttons.forEach(b=>{b.disabled=reduced.matches;b.setAttribute('aria-pressed',String(paused));b.setAttribute('aria-label',paused?'Resume site motion':'Pause site motion');b.textContent=reduced.matches?'MOTION REDUCED':paused?'MOTION ↗':'MOTION Ⅱ';});document.querySelectorAll('[data-motion-toggle]').forEach(b=>{b.disabled=reduced.matches;b.setAttribute('aria-pressed',String(paused));b.textContent=reduced.matches?'MOTION REDUCED':paused?'RESUME MOTION ↗':'PAUSE MOTION Ⅱ';});schedule();}
 buttons.forEach(b=>b.addEventListener('click',()=>{window.NUC_DOTS?.setPaused(!window.NUC_DOTS.isPaused());motion();}));document.querySelectorAll('[data-motion-toggle]').forEach(b=>b.addEventListener('click',motion));reduced.addEventListener('change',motion);
 let frame=0;const scenes=[...document.querySelectorAll('.module-scene')],story=document.querySelector('.module-scroll-story');
 function paint(){frame=0;const still=reduced.matches||window.NUC_DOTS?.isPaused()||document.hidden;for(const scene of scenes){const r=scene.getBoundingClientRect();if(r.bottom<0||r.top>innerHeight)continue;const shift=still?0:Math.max(-60,Math.min(60,(innerHeight/2-(r.top+r.height/2))/innerHeight*85));scene.style.setProperty('--mosaic-shift',shift.toFixed(2)+'px');scene.style.setProperty('--module-lift',(-shift*.65).toFixed(2)+'px');}
  if(story){const r=story.getBoundingClientRect(),travel=Math.max(1,r.height-innerHeight),progress=Math.max(0,Math.min(1,-r.top/travel));story.style.setProperty('--story-progress',still?'0.5':progress.toFixed(3));}
 }
 function schedule(){if(!frame&&!document.hidden)frame=requestAnimationFrame(paint);}
 addEventListener('scroll',schedule,{passive:true});addEventListener('resize',schedule,{passive:true});document.addEventListener('visibilitychange',()=>{document.body.classList.toggle('motion-sleep',document.hidden);schedule();});new ResizeObserver(schedule).observe(document.body);
 window.NUC_MODULAR={matrix,segments,refresh:personalize};addEventListener('nucWorkbenchChange',personalize);addEventListener('nucLiveWatchChange',personalize);addEventListener('storage',()=>{personalize();});apply();motion();
})();
