/* Account-owned X Money payout plans. No transfer or settlement is inferred from a draft. */
(()=>{
 const client=window.NUC_BILLING,host=document.querySelector('#connections');if(!client||!host)return;
 const section=document.createElement('details');section.className='connection-details';section.id='creatorPayouts';section.innerHTML='<summary>Pay holders, promoters and collaborators +</summary><p class="connection-copy">Prepare a USD payment for an X account. Complete the transfer in X Money. Saved plans do not move funds or confirm that a recipient holds your token.</p><form id="payoutPlan" class="connection-form"><label>COIN WORKSPACE<select id="payoutCoin" required><option value="">Choose your coin workspace</option></select></label><div class="connection-fields"><label>RECIPIENT ON X<input id="payoutHandle" required maxlength="16" pattern="@?[A-Za-z0-9_]{1,15}" placeholder="@creator"></label><label>PAYMENT TYPE<select id="payoutKind"><option value="holder">Holder reward</option><option value="promotion">Promotion</option><option value="collaborator">Collaborator</option><option value="other">Other</option></select></label></div><label>AMOUNT (USD)<input id="payoutAmount" required inputmode="decimal" pattern="[0-9]+(\\.[0-9]{1,2})?" placeholder="25.00"></label><label>NOTE<input id="payoutNote" maxlength="300" placeholder="Purpose or agreed deliverable"></label><div class="connection-actions"><button type="submit">Save payout plan</button><button id="payoutRefresh" type="button">Refresh</button><a href="https://money.x.com/" target="_blank" rel="noopener noreferrer">Open X Money ↗</a></div></form><p id="payoutNotice" role="status" class="connection-notice"></p><div id="payoutRows"></div>';host.querySelector(':scope > div').append(section);
 const q=id=>document.getElementById(id),api=(path,body)=>client.request(path,body===undefined?{}:{method:'POST',body:JSON.stringify(body)});let requestKey=null,requestBody=null;
 async function refresh(){const [coins,data]=await Promise.all([api('ai/coins'),api('payouts')]);const before=q('payoutCoin').value;q('payoutCoin').replaceChildren();for(const c of coins.coins){const o=document.createElement('option');o.value=c.id;o.textContent=c.name+' · '+c.ticker;q('payoutCoin').append(o);}if([...q('payoutCoin').options].some(o=>o.value===before))q('payoutCoin').value=before;q('payoutRows').replaceChildren();for(const p of data.payouts.filter(p=>p.status==='draft')){const row=document.createElement('div');row.className='connection-line';const copy=document.createElement('div'),name=document.createElement('strong'),meta=document.createElement('small');name.textContent='@'+p.handle+' · $'+(p.amountCents/100).toFixed(2);meta.textContent=p.kind+' · Draft / not paid'+(p.note?' · '+p.note:'');copy.append(name,meta);const link=document.createElement('a');link.href='https://x.com/'+encodeURIComponent(p.handle);link.target='_blank';link.rel='noopener noreferrer';link.textContent='Profile ↗';const cancel=document.createElement('button');cancel.type='button';cancel.textContent='Cancel';cancel.addEventListener('click',()=>run(cancel,async()=>{await api('payouts/'+p.id+'/cancel',{});await refresh();}));row.append(copy,link,cancel);q('payoutRows').append(row);}}
 async function run(button,task){button.disabled=true;try{await task();}catch(e){q('payoutNotice').textContent=e.message;}finally{button.disabled=false;}}
 q('payoutPlan').addEventListener('submit',event=>{event.preventDefault();run(event.submitter,async()=>{const value=q('payoutAmount').value.trim();if(!/^[0-9]+(\.[0-9]{1,2})?$/.test(value))throw Error('Use a USD amount with at most two decimal places.');const [whole,fraction='']=value.split('.');const cents=Number(whole)*100+Number(fraction.padEnd(2,'0'));if(!Number.isSafeInteger(cents)||cents<1||cents>100000000)throw Error('Choose an amount between $0.01 and $1,000,000.');const body={coinId:q('payoutCoin').value,handle:q('payoutHandle').value.trim(),kind:q('payoutKind').value,amountCents:cents,note:q('payoutNote').value.trim()},serialized=JSON.stringify(body);if(requestBody!==serialized){requestKey=client.uuid();requestBody=serialized;}await api('payouts',{...body,requestKey});requestBody=requestKey=null;q('payoutNotice').textContent='Payout plan saved. No money was transferred. Open X Money to complete the payment after checking the recipient.';await refresh();});});
 q('payoutRefresh').addEventListener('click',event=>run(event.target,refresh));
 client.ready.then(state=>{if(state.user)refresh().then(()=>{if(location.hash==='#creatorPayouts'){section.open=true;section.scrollIntoView({block:'start'});}}).catch(e=>q('payoutNotice').textContent=e.message);else q('payoutNotice').textContent='Sign in and create a coin workspace to plan payouts.';});
})();
