/* Finish the familiar pages: artwork depth and project identity, without a new page structure. */
(() => {
 const reduced=matchMedia('(prefers-reduced-motion:reduce)'),layers=[...document.querySelectorAll('#heroWave,.home-build>canvas,.registry-pixel-layer,.classic-explore .dot-horizon,.classic-explore #explorePulseCanvas,.identity-orbit>canvas')];
 let frame=0;
 function paint(){frame=0;const still=reduced.matches||window.NUC_DOTS?.isPaused()||document.hidden;layers.forEach((el,index)=>{const host=el.closest('section,.signature-art,.terminal-market,.identity-orbit')||el.parentElement,r=host.getBoundingClientRect();if(r.bottom<0||r.top>innerHeight)return;const shift=still?0:Math.max(-35,Math.min(35,(innerHeight/2-(r.top+r.height/2))/innerHeight*(index%2?35:60)));el.style.setProperty('--refined-depth',shift.toFixed(2)+'px');});}
 function schedule(){if(!frame&&!document.hidden)frame=requestAnimationFrame(paint);}
 addEventListener('scroll',schedule,{passive:true});addEventListener('resize',schedule,{passive:true});document.addEventListener('visibilitychange',schedule);reduced.addEventListener('change',schedule);new MutationObserver(schedule).observe(document.body,{attributes:true,attributeFilter:['class']});new ResizeObserver(schedule).observe(document.body);schedule();
 const form=document.querySelector('#projectBriefForm');if(form){const update=()=>{const set=(selector,value)=>{const el=document.querySelector(selector);if(el)el.textContent=value;};set('[data-studio-identity]',form.elements.name.value.trim()||'Your project, taking shape.');set('[data-studio-purpose]',form.elements.purpose.value.trim()||'A useful reason to exist.');set('[data-studio-milestone]',form.elements.milestone.value.trim()||'A first thing to ship.');};form.addEventListener('input',update);form.addEventListener('change',update);document.querySelectorAll('[data-studio-kit]').forEach(b=>b.addEventListener('click',()=>queueMicrotask(update)));update();}
 const coinSupply=document.querySelector('#coinSupplyPreview');if(coinSupply){const update=()=>{const supply=document.querySelector('[data-identity-supply]'),venue=document.querySelector('[data-identity-venue]');if(supply)supply.textContent=coinSupply.textContent;if(venue)venue.textContent=document.querySelector('#coinVenuePreview').textContent;};new MutationObserver(update).observe(coinSupply.parentElement.parentElement,{childList:true,subtree:true});update();}
 document.querySelectorAll('[data-market-view]').forEach(b=>b.addEventListener('click',()=>{document.querySelector('#marketResults').classList.toggle('compact',b.dataset.marketView==='compact');document.querySelectorAll('[data-market-view]').forEach(x=>{x.setAttribute('aria-pressed',String(x===b));x.classList.toggle('active',x===b);});}));
})();
