/* Native server apps: account-owned files, with actual shared disk accounting. */
(() => {
 const client=window.NUC_BILLING,state={mode:'loading',workspaces:[],catalog:[],error:null},inventories=new Map(),pending=new Map();
 const el=(tag,cls,text)=>{const e=document.createElement(tag);e.className=cls;if(text!==undefined)e.textContent=text;return e;},size=n=>n>=1048576?(n/1048576).toFixed(2)+' MiB':n>=1024?(n/1024).toFixed(1)+' KiB':n+' B';
 const ready=(async()=>{try{const response=await fetch('data/tool-catalog.json');if(!response.ok)throw Error('The app catalog is unavailable.');state.catalog=(await response.json()).apps.filter(a=>a.installable);await client?.ready;if(!client?.state.user){state.mode='guest';return state;}const data=await client.request('workspaces');state.workspaces=(data.workspaces||[]).filter(w=>w.server&&w.server.template==='static-website'&&w.server.status!=='missing');state.mode='account';}catch(e){state.mode='unavailable';state.error=e.message;}return state;})();
 function validated(data,id){const s=data?.storage;if(data?.server?.workspaceId!==id||!Array.isArray(data.apps)||!s||!Number.isInteger(s.limitBytes)||s.limitBytes<1||!Number.isInteger(s.usedBytes)||s.usedBytes<0||!Number.isInteger(s.availableBytes)||s.availableBytes<0)throw Error('Server storage could not be verified. Refresh to try again.');return data;}
 async function inventory(id,force=false){await ready;if(!state.workspaces.some(w=>w.id===id))throw Error('Choose one of your own website servers.');if(!force&&inventories.has(id))return inventories.get(id);if(pending.has(id))return pending.get(id);const task=client.request('workspaces/'+encodeURIComponent(id)+'/apps').then(data=>{validated(data,id);inventories.set(id,data);return data;}).finally(()=>pending.delete(id));pending.set(id,task);return task;}
 async function change(id,appId,operation){if(!state.catalog.some(a=>a.id===appId))throw Error('Choose an app from this store.');if(!state.workspaces.some(w=>w.id===id))throw Error('Choose one of your own website servers.');const data=validated(await client.request('workspaces/'+encodeURIComponent(id)+'/apps/'+encodeURIComponent(appId)+'/'+operation,{method:'POST',body:'{}'}),id);inventories.set(id,data);dispatchEvent(new CustomEvent('nuc-server-apps-change',{detail:{workspaceId:id}}));return data;}
 function meter(data){const box=el('div',''),text=el('p','tool-install-state',size(data.storage.usedBytes)+' used / '+size(data.storage.limitBytes)+' allocated · '+size(data.storage.availableBytes)+' free'),meter=el('div','app-disk-meter'),fill=el('i','');fill.style.width=Math.min(100,data.storage.usedBytes/data.storage.limitBytes*100)+'%';fill.classList.toggle('full',data.storage.overQuota);meter.append(fill);box.append(text,meter);return box;}
 function appURL(data,app){try{const url=new URL(state.workspaces.find(w=>w.id===data.server.workspaceId)?.server.url||data.server.url);if(!['http:','https:'].includes(url.protocol)||url.username||url.password||!/^\/apps\/[a-z][a-z0-9-]*\/$/.test(app.path))return null;url.search='';url.hash='';if(!url.pathname.endsWith('/'))url.pathname+='/';return new URL(app.path.slice(1),url).href;}catch{return null;}}
 function signIn(parent,text){const copy=el('p','tool-install-state',text),link=el('a','store-primary','Sign in to install ↗');link.href=client?.state.externalUrl||'billing.html';parent.append(copy,link);}
 async function attach(parent,app){const panel=el('section','tool-install-panel');panel.setAttribute('aria-label','Install '+app.name+' on your server');parent.append(panel);panel.append(el('p','tool-install-state','Reading your server workspaces…'));await ready;if(!panel.isConnected)return;panel.replaceChildren();if(state.mode==='guest'){signIn(panel,'Install '+size(app.bytes)+' of app files on a website server you own. Personal edits stay in your browser.');return;}if(state.mode==='unavailable'){panel.append(el('p','tool-install-state',state.error));return;}if(!state.workspaces.length){panel.append(el('p','tool-install-state','Create or allocate a website server before installing an app.'));const link=el('a','store-primary','Choose a server ↗');link.href='hosting.html';panel.append(link);return;}
  const label=el('label','','Install on your server'),select=el('select','');select.setAttribute('aria-label','Server for app installation');for(const w of state.workspaces){const option=el('option','',w.project+' · '+(w.server.nodeName||w.server.nodeId||'Pi')+' · '+w.server.status);option.value=w.id;select.append(option);}label.append(select);const disk=el('div',''),button=el('button','store-primary','Check disk space'),remove=el('button','tool-assign','Remove app'),notice=el('p','tool-install-state');notice.setAttribute('role','status');button.type=remove.type='button';remove.hidden=true;panel.append(label,disk,button,remove,notice);let generation=0,current=null,busy=false;
  async function render(force=false){const version=++generation;current=null;button.disabled=true;remove.hidden=true;notice.textContent='Checking server storage…';try{const data=await inventory(select.value,force);if(version!==generation||!panel.isConnected)return;current=data;disk.replaceChildren(meter(data));const installed=data.apps.find(a=>a.id===app.id),workspace=state.workspaces.find(w=>w.id===select.value);remove.hidden=!installed;button.textContent=installed?(installed.integrity?'Installed ✓':'Files changed · reinstall after removal'):'Install app · '+size(app.bytes)+' ＋';button.disabled=!!installed||busy||!workspace.canManageServer||data.storage.availableBytes<app.bytes;remove.disabled=busy;notice.textContent=installed?(installed.integrity?'Installed on '+workspace.project+'. These files use '+size(installed.bytes)+' of its disk space.':'The app files have changed. Remove and reinstall to restore the verified package.'):!workspace.canManageServer?'This server enrollment is inactive.':data.storage.availableBytes<app.bytes?'There is not enough space for this app. Remove an app or reduce your website files.':'App files share your website disk allowance. No additional server slot is used.';if(installed&&data.server.status==='running'){const url=appURL(data,installed);if(url){const link=el('a','tool-setup-link','Open installed app ↗');link.href=url;link.target='_blank';link.rel='noopener noreferrer';disk.append(link);}}}catch(e){if(version!==generation)return;disk.replaceChildren();button.textContent='Installation unavailable';notice.textContent=e.message;}}
  async function act(operation){if(busy||!current)return;busy=true;select.disabled=button.disabled=remove.disabled=true;notice.textContent=operation==='install'?'Writing verified app files to your server…':'Removing app files and releasing disk space…';try{if(operation==='install'&&window.NUC_TRANSFER){const workspaceId=select.value,workspace=state.workspaces.find(w=>w.id===workspaceId);await window.NUC_TRANSFER.run({title:app.name,kind:'SERVER APP / INSTALLATION',badge:'APP',bytes:app.bytes,destination:workspace.project,phase:'Installing verified app files…',success:'Installed on your server',completeNote:'Open the installed app from this server’s inventory. Personal edits stay in your browser.',verify:async()=>{const data=await inventory(workspaceId,true);return [{label:'Signed in to your account',ok:!!client.state.user},{label:'Owned website server · active enrollment',ok:!!workspace.canManageServer},{label:'Static website runtime',ok:workspace.server.template==='static-website'},{label:size(data.storage.availableBytes)+' free · '+size(app.bytes)+' required',ok:data.storage.availableBytes>=app.bytes},{label:'No additional server slot needed',ok:true},{label:'Package integrity checked during installation',ok:null}];},task:async update=>{const data=await change(workspaceId,app.id,'install');update('Verifying installed files…');if(!data.apps?.some(a=>a.id===app.id&&a.integrity))throw Error('Installation could not be verified. Refresh your server inventory.');return data;}});}else await change(select.value,app.id,operation);await render();}catch(e){await render(true);notice.textContent=e.message;}finally{busy=false;select.disabled=false;remove.disabled=false;if(!current?.apps.some(a=>a.id===app.id)&&current?.storage.availableBytes>=app.bytes&&state.workspaces.find(w=>w.id===select.value)?.canManageServer)button.disabled=false;}}
  select.addEventListener('change',()=>render());button.addEventListener('click',()=>act('install'));remove.addEventListener('click',()=>act('remove'));render();
 }
 async function mountInstalled(){let host=document.getElementById('deskTools')||document.querySelector('.account-app-library');if(!host)return;const panel=el('section','installed-apps-panel');panel.setAttribute('aria-label','Installed server apps');host.append(panel);panel.append(el('h3','','On your server.'),el('p','','Installed apps and the disk space they use.'));await ready;if(state.mode==='guest'){signIn(panel,'Sign in to see apps installed on your servers.');return;}if(state.mode==='unavailable'){panel.append(el('p','',state.error));return;}if(!state.workspaces.length){panel.append(el('p','','Your apps will appear here after you allocate a website server.'));return;}const label=el('label','tool-target-label','Website server'),select=el('select','');select.setAttribute('aria-label','Server app inventory');for(const w of state.workspaces){const o=el('option','',w.project);o.value=w.id;select.append(o);}label.append(select);const disk=el('div',''),list=el('div','installed-apps-list'),notice=el('p','');notice.setAttribute('role','status');panel.append(label,disk,list,notice);let version=0;
  async function render(force=false){const n=++version;list.replaceChildren();notice.textContent='Reading installed app files…';try{const data=await inventory(select.value,force);if(n!==version)return;disk.replaceChildren(meter(data));list.replaceChildren();for(const app of data.apps){const info=state.catalog.find(a=>a.id===app.id);if(!info)continue;const row=el('div','installed-app-row'),logo=el('img','');logo.src=info.logo;logo.alt='';const copy=el('div','');copy.append(el('strong','',app.name),el('small','',size(app.bytes)+' · '+(app.integrity?'Installed':'Files changed')));row.append(logo,copy);const url=appURL(data,app);if(url&&data.server.status==='running'){const link=el('a','','Open ↗');link.href=url;link.target='_blank';link.rel='noopener noreferrer';row.append(link);}const remove=el('button','','Remove');remove.type='button';remove.setAttribute('aria-label','Remove '+app.name+' from this server');const workspaceId=select.value;remove.onclick=async()=>{remove.disabled=true;try{await change(workspaceId,app.id,'remove');}catch(e){notice.textContent=e.message;remove.disabled=false;}};row.append(remove);list.append(row);}notice.textContent=data.apps.length?'App files use '+size(data.storage.appBytes)+'. Website files use '+size(data.storage.websiteBytes)+'.':'No apps installed yet. Open the store to choose one.';}catch(e){if(n!==version)return;disk.replaceChildren();list.replaceChildren();notice.textContent=e.message;}}
  select.addEventListener('change',()=>render());addEventListener('nuc-server-apps-change',e=>{if(e.detail.workspaceId===select.value)render();});render();
 }
 window.NUC_SERVER_APPS={state,ready,inventory,install:(id,app)=>change(id,app,'install'),remove:(id,app)=>change(id,app,'remove'),attach,size};
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mountInstalled,{once:true});else mountInstalled();
 document.querySelectorAll('.telemetry-dots').forEach(c=>window.NUC_DOTS?.mount(c));
 if(new URLSearchParams(location.search).get('preview')==='1')for(const link of document.querySelectorAll('a[href]')){const url=new URL(link.href,location.href);if(url.origin===location.origin&&url.pathname.endsWith('.html')&&!url.pathname.includes('/assets/')){url.searchParams.set('preview','1');link.href=url.pathname+url.search+url.hash;}}
})();
