/* Guided native server provisioning. Selection preferences never execute shell commands. */
(() => {
 const root=document.getElementById('serverSetup'),client=window.NUC_BILLING;if(!root||!client)return;
 const commands={files:{label:'ls -lah',command:'ls -lah'},storage:{label:'df -h',command:'df -h'},processes:{label:'ps',command:'ps'},identity:{label:'whoami',command:'whoami'},nginx:{label:'nginx -v',command:'nginx -v'},clock:{label:'date',command:'date'}};
 const modelNames={'nucaloric:tiny':'Tiny','nucaloric:small':'Small','nucaloric:reasoning':'Reasoning','nucaloric:code':'Code'};
 const titles=['Choose your server.','A few useful things.','Make the connections.','Give it a name.','Ready when you are.'];
 const subtitles=['Start fresh, or make an existing server your own.','Choose the apps to install, your command shortcuts and shared AI models.','Keep your files, tools and intelligence close to the work.','Something that feels like your place to build.','Review what will change. Then we’ll put it together.'];
 const q=id=>document.getElementById(id),node=(tag,cls,text)=>{const n=document.createElement(tag);n.className=cls||'';if(text!==undefined)n.textContent=text;return n;};
 const defaults={target:'new',tier:'basic',name:'',apps:[],models:['nucaloric:tiny'],commands:['files','storage'],integrations:['files','ai'],repository:'',step:0};
 let draft={...defaults},workspaces=[],catalog=[],modelState={connected:false,models:[]},github={configured:false,connected:false},balance=0,paymentRequired=true,busy=false,account=false,maximum=0,purchase=null;
 function key(){return 'nucServerSetup:'+client.state.user?.email;}
 function persist(){if(account)try{sessionStorage.setItem(key(),JSON.stringify({...draft,purchase}));}catch{}}
 function say(message,error=false){q('setupStatus').textContent=message;q('setupStatus').classList.toggle('error',error);}
 function heading(label){return node('div','setup-group-title',label);}
 function field(label,type='text'){const l=node('label','setup-field',label),input=node('input');input.type=type;l.append(input);return {l,input};}
 function option(group,id,title,copy,icon,meta){const label=node('label','setup-option'),input=node('input');input.type='checkbox';input.checked=draft[group].includes(id);input.addEventListener('change',()=>{draft[group]=input.checked?[...new Set([...draft[group],id])]:draft[group].filter(x=>x!==id);persist();});const graphic=node('span','setup-option-icon');if(icon?.includes('/')){const img=node('img');img.src=icon;img.alt='';graphic.append(img);}else graphic.textContent=icon||'✳';const text=node('span');text.append(node('strong','',title),node('small','',copy));if(meta)text.append(node('em','',meta));label.append(input,graphic,text);return label;}
 function selectTarget(value){draft.target=value;const w=workspaces.find(w=>w.id===value);if(w){const saved=w.plan.setup;draft.name=w.project;draft.tier=w.term?.tier||w.plan.tier||'basic';draft.repository=w.plan.repository||'';if(saved)for(const group of ['commands','models','apps','integrations'])if(Array.isArray(saved[group]))draft[group]=[...saved[group]];}else if(value==='new')draft.name='';persist();render();}
 function render(){const stage=q('setupStage');stage.replaceChildren();stage.append(node('div','setup-step-label'));stage.firstChild.append(node('span','','SERVER SETUP / '+String(draft.step+1).padStart(2,'0')),node('span','',String(draft.step+1)+' of 5'));stage.append(node('h2','',titles[draft.step]),node('p','',subtitles[draft.step]));
  document.querySelectorAll('[data-setup-step]').forEach(b=>{const index=Number(b.dataset.setupStep);b.setAttribute('aria-current',index===draft.step?'step':'false');b.classList.toggle('complete',index<draft.step);b.disabled=busy||index>maximum;b.querySelector('i').textContent=index<draft.step?'✓':String(index+1).padStart(2,'0');});
  q('setupBack').disabled=busy||draft.step===0;q('setupNext').disabled=busy;q('setupNext').textContent=draft.step===4?(draft.target==='new'?'Create server ↗':'Apply setup ↗'):'Continue ↗';q('setupNext').hidden=false;
  if(busy){stage.append(node('div','setup-note','Applying your reviewed setup. Keep this page open until the final disk check completes.'));return;}
  if(!account){stage.append(node('div','setup-note','Sign in to connect this setup to your Paymenter profile, servers and balance.'));const b=node('button','setup-link-button','Sign in to your account ↗');b.type='button';b.dataset.accountOpen='';stage.append(b);q('setupNext').disabled=true;return;}
  if(draft.step===0){const l=node('label','setup-field','Server'),select=node('select');select.setAttribute('aria-label','Server to set up');for(const [id,name] of [['new','Create a new server'],...workspaces.map(w=>[w.id,w.project+' · '+(w.server?.nodeName||'Pi')])]){const o=node('option','',name);o.value=id;select.append(o);}select.value=draft.target;l.append(select);stage.append(l);select.onchange=()=>selectTarget(select.value);
   if(draft.target==='new'){stage.append(heading('YOUR MONTHLY WORKSPACE'));const plans=node('div','setup-options');for(const [id,title,cost,copy] of [['basic','Basic','$1.50 / month','Website hosting, terminal and shell scripts.'],['full','Full','$2.00 / month','Plus GitHub deployment, AI knowledge and shared files.']]){const label=node('label','setup-option'),input=node('input');input.type='radio';input.name='setupTier';input.checked=draft.tier===id;input.onchange=()=>{draft.tier=id;persist();render();};const text=node('span');text.append(node('strong','',title),node('small','',copy),node('em','',cost));label.append(input,text);plans.append(label);}stage.append(plans);stage.append(node('div','setup-note',paymentRequired?'One prepaid calendar month. Renew manually. Your server balance: $'+(balance/100).toFixed(2)+'.':'Prices shown are the normal monthly rates. Payment is temporarily waived for your account.'));
   }else{const w=workspaces.find(w=>w.id===draft.target);stage.append(node('div','setup-note','Your existing server and billing term stay in place. This setup changes its name, chosen apps and workspace preferences.'));if(w?.plan.setup?.apps?.length)stage.append(node('p','setup-note','Previously installed apps are kept. Remove unwanted apps from My tools.'));}
   const card=node('div','setup-server-card'),img=node('img');img.src='assets/reference/server-form-cutout.png';img.alt='';const info=node('div');info.append(node('strong','','A small machine. Room for an idea.'),node('p','','32 MB RAM · 0.25 CPU\n1 MiB shared by your website and installed apps.'));card.append(img,info);stage.append(card);
  }
  if(draft.step===1){stage.append(heading('PREINSTALL YOUR APPS'));const apps=node('div','setup-options');for(const app of catalog)apps.append(option('apps',app.id,app.name,app.summary||app.description||'Ready to use on your server.',app.logo,(app.bytes/1024).toFixed(1)+' KiB · actual server files'));stage.append(apps);
   stage.append(heading('YOUR TERMINAL SHORTCUTS'));const pills=node('div','setup-commands');for(const [id,c] of Object.entries(commands)){const l=node('label'),input=node('input');input.type='checkbox';input.checked=draft.commands.includes(id);input.onchange=()=>{draft.commands=input.checked?[...draft.commands,id]:draft.commands.filter(x=>x!==id);persist();};l.append(input,node('span','',c.label));pills.append(l);}stage.append(pills);stage.append(node('p','setup-note','These commands are already available in your Alpine terminal. Shortcuts fill the prompt; you decide when to run them.'));
   stage.append(heading('SHARED AI / OPTIONAL'));const models=node('div','setup-options setup-models');for(const [id,name] of Object.entries(modelNames)){const available=modelState.connected&&modelState.models.some(m=>m.id===id&&m.installed);const l=option('models',id,name,id==='nucaloric:tiny'||id==='nucaloric:small'?'Free shared model':'$0.50 / 1,000 tokens',null,available?'Worker online':modelState.connected?'Not installed on worker':'Worker offline');l.querySelector('.setup-option-icon').remove();models.append(l);}stage.append(models);stage.append(node('p','setup-note',modelState.connected?'These models run on the shared inference worker. They are connected to your workspace rather than installed inside the website server.':'The inference worker is offline. Your model preferences can be saved now; model use becomes available when it reconnects.'));
  }
  if(draft.step===2){const options=node('div','setup-options');options.append(option('integrations','files','Files workspace','Manage your website assets and private account documents.','▱','Included'),option('integrations','ai','Shared AI','Keep your preferred models next to your terminal.','✳',modelState.connected?'Inference worker online':'Available when the worker reconnects'),option('integrations','github','GitHub','Save the repository you want to deploy later.','assets/partners/github.svg',github.connected?'Account connected':github.configured?'Connect from dashboard':'Provider connection pending'));stage.append(options);const f=field('Repository · optional','url');f.input.placeholder='https://github.com/you/project';f.input.value=draft.repository;f.input.oninput=()=>{draft.repository=f.input.value;persist();};f.l.append(node('small','','Saving a repository does not grant access to it or deploy code. Connect GitHub from Connections when you are ready.'));stage.append(f.l);const note=node('div','setup-note','Paymenter is already connected. Your account profile, owned servers and balance are shared automatically.');stage.append(note);}
  if(draft.step===3){const f=field('SERVER NAME');f.l.classList.add('setup-name-field');f.input.id='setupServerName';f.input.maxLength=60;f.input.required=true;f.input.placeholder='Your next good idea';f.input.value=draft.name;f.input.oninput=()=>{draft.name=f.input.value;persist();q('setupNamePreview').textContent=draft.name.trim()||'Your server';};f.l.append(node('small','','Up to 60 characters. You can change this later without moving your files.'));stage.append(f.l);const card=node('div','setup-server-card'),img=node('img');img.src='assets/reference/server-form-cutout.png';img.alt='';const copy=node('div'),title=node('strong','',draft.name.trim()||'Your server');title.id='setupNamePreview';copy.append(title,node('p','',client.state.user.name+' / NUCALORIC workspace'));card.append(img,copy);stage.append(card);}
  if(draft.step===4){const size=catalog.filter(a=>draft.apps.includes(a.id)).reduce((n,a)=>n+a.bytes,0),review=node('div','setup-review');const rows=[['SERVER',draft.name],['TARGET',draft.target==='new'?'New '+draft.tier+' server':'Existing server'],['APPS',catalog.filter(a=>draft.apps.includes(a.id)).map(a=>a.name).join(', ')||'None'],['COMMANDS',draft.commands.map(id=>commands[id]?.label).filter(Boolean).join(', ')||'None'],['AI PREFERENCES',draft.models.map(id=>modelNames[id]).join(', ')||'None'],['CONNECTIONS',draft.integrations.map(x=>({files:'Files',ai:'AI',github:'GitHub'})[x]).join(', ')||'None'],['APP DISK', (size/1024).toFixed(1)+' KiB / 1 MiB shared'],['MONTHLY PRICE',draft.tier==='full'?'$2.00 / month':'$1.50 / month'],['TODAY',draft.target==='new'?(paymentRequired?(draft.tier==='full'?'$2.00':'$1.50')+' from server credits':'$0.00 · temporary account access'):'$0.00 · current term continues']];for(const [label,value] of rows){const r=node('div',label==='TODAY'?'setup-review-cost':'');r.append(node('span','',label),node('b','',value));review.append(r);}stage.append(review);if(draft.target==='new'){const consent=node('label','setup-consent'),input=node('input');input.type='checkbox';input.id='setupConsent';consent.append(input,node('span','',paymentRequired?'I approve one prepaid calendar month. Deduct '+(draft.tier==='full'?'$2.00':'$1.50')+' from my server credits when the server is allocated.':'Create my monthly server. Payment is temporarily waived; no server credits will be deducted.'));stage.append(consent);}stage.append(node('div','setup-note','Apps are installed as real server files and counted against disk space. Model use and GitHub deployment happen when you choose to use them.'));}
 }
 async function next(){if(busy)return;say('');if(draft.step===0&&draft.target==='new'&&(!client.state.provisioner.connected||client.state.provisioner.available===0)){say('No server slots are available right now. Choose an existing server or try again shortly.',true);return;}
  if(draft.step===2&&draft.repository&&!/^https:\/\/github\.com\/[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+\/?$/.test(draft.repository)){say('Use a GitHub repository URL, such as https://github.com/you/project.',true);return;}
  if(draft.step===3&&!draft.name.trim()){say('Give your server a name to continue.',true);q('setupServerName').focus();return;}
  if(draft.step<4){draft.step++;maximum=Math.max(maximum,draft.step);persist();render();return;}
  if(draft.target==='new'&&!q('setupConsent')?.checked){say(paymentRequired?'Review the price and approve the prepaid month before creating your server.':'Review your setup and approve creating the server.',true);return;}
  busy=true;render();const stage=q('setupStage'),progress=node('ol','setup-progress-list');stage.append(progress);
  const mark=text=>{const li=node('li','',text);progress.append(li);return li;};let id=draft.target;
  try{if(id==='new'){
    const price=draft.tier==='full'?200:150;if(paymentRequired&&balance<price){throw Error('Add server credits first. Your setup choices are saved; return here after funding your balance.');}
    const plan={version:1,project:draft.name.trim(),source:'paymenter',hardware:'pi',workload:'web',compute:'cpu',repository:draft.repository,tokenMint:'',access:'private',endpoint:'',nodeId:'main'};
    const hash=JSON.stringify({tier:draft.tier,plan});if(!purchase||purchase.hash!==hash)purchase={key:client.uuid(),hash};persist();const li=mark('Allocating your server…');const result=await client.request('commerce/servers',{method:'POST',body:JSON.stringify({requestKey:purchase.key,tier:draft.tier,plan})});if(!result.workspaceId)throw Error('Your server allocation could not be verified.');id=result.workspaceId;draft.target=id;persist();li.textContent='✓ Server allocated';li.classList.add('done');
   }else{const w=workspaces.find(w=>w.id===id);if(w?.canAllocate&&!w.server){const li=mark('Allocating the enrolled server…');await client.request('workspaces/'+id+'/server/create',{method:'POST',body:'{}'});li.textContent='✓ Server allocated';li.classList.add('done');}}
   for(const app of catalog.filter(a=>draft.apps.includes(a.id))){const li=mark('Installing '+app.name+'…');const result=await client.request('workspaces/'+id+'/apps/'+app.id+'/install',{method:'POST',body:'{}'});if(!result.apps?.some(a=>a.id===app.id&&a.integrity))throw Error(app.name+' installation could not be verified.');li.textContent='✓ '+app.name+' installed';li.classList.add('done');}
   const li=mark('Saving your name and workspace preferences…');await client.request('workspaces/'+id+'/setup',{method:'POST',body:JSON.stringify({name:draft.name.trim(),commands:draft.commands,models:draft.models,apps:draft.apps,integrations:draft.integrations,repository:draft.repository||null})});li.textContent='✓ Workspace saved to your account';li.classList.add('done');const verified=await client.request('workspaces/'+id+'/files');if(!verified.storage||verified.server?.workspaceId!==id)throw Error('The final disk check could not be verified.');const disk=mark('✓ Disk verified · '+(verified.storage.usedBytes/1024).toFixed(1)+' KiB used');disk.classList.add('done');try{sessionStorage.removeItem(key());localStorage.setItem('nucRuntimeSelected',id);}catch{}q('setupNext').hidden=true;q('setupBack').disabled=true;const link=node('a','setup-link-button','Open your workspace ↗');link.href='dashboard.html?server='+encodeURIComponent(id)+'#deskFiles';progress.after(link);say('Your server is set up. Files and shortcuts are ready in your dashboard.');
  }catch(e){say(e.message,true);if(draft.target!=='new'&&id!=='new'){say(e.message+' Completed steps are kept. Retry to finish setup.',true);const updated=await client.request('workspaces').catch(()=>null);if(updated)workspaces=updated.workspaces.filter(w=>w.canManageServer||w.canAllocate);}
   if(draft.target==='new'&&paymentRequired&&balance<(draft.tier==='full'?200:150)){const a=node('a','setup-link-button','Add server credits ↗');a.href='billing.html#cryptoCheckout';stage.append(a);}q('setupNext').disabled=false;q('setupBack').disabled=false;
  }finally{busy=false;}
 }
 q('setupNext').onclick=next;q('setupBack').onclick=()=>{if(busy)return;draft.step=Math.max(0,draft.step-1);persist();say('');render();};document.querySelectorAll('[data-setup-step]').forEach(b=>b.onclick=()=>{if(busy)return;draft.step=Number(b.dataset.setupStep);persist();say('');render();});
 (async()=>{await client.ready;account=!!client.state.user;q('setupAccount').textContent=account?client.state.user.email||client.state.user.name:'Connect your account';if(!account){render();return;}say('Reading your servers and available features…');try{const [records,tools,credits,ai,gh]=await Promise.all([client.request('workspaces'),fetch('data/tool-catalog.json').then(r=>r.json()),client.request('commerce'),client.request('ai/coins').catch(()=>({ai:{connected:false,models:[]}})),client.request('github').catch(()=>({configured:false,connected:false}))]);workspaces=records.workspaces.filter(w=>w.canManageServer||w.canAllocate);client.state.provisioner=records.provisioner||client.state.provisioner;catalog=tools.apps.filter(a=>a.installable);balance=credits.balances.server;paymentRequired=credits.serverPayment?.required!==false;modelState=ai.ai;github=gh;try{const saved=JSON.parse(sessionStorage.getItem(key())||'null');if(saved){draft={...defaults,...saved};purchase=saved.purchase||null;draft.step=Math.min(4,Math.max(0,Number(draft.step)||0));maximum=draft.step;}}catch{}const target=new URLSearchParams(location.search).get('server');if(target&&workspaces.some(w=>w.id===target)){selectTarget(target);}else if(draft.target!=='new'&&!workspaces.some(w=>w.id===draft.target))draft.target='new';render();say('');}catch(e){render();q('setupNext').disabled=true;say(e.message,true);}})();
 window.NUC_SETUP_COMMANDS=commands;
})();
