/* Four continuous columns: navigation, work, conversation and inline details. */
(()=>{
 const wrap=document.querySelector('.account-main > .wrap'),grid=wrap?.querySelector('.dev-dashboard-grid');if(!grid)return;
 const q=id=>document.getElementById(id),make=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
 document.body.classList.add('creator-desk');
 const shell=make('div','desk-shell'),rail=make('aside','desk-rail'),library=make('aside','desk-library'),canvas=make('section','desk-canvas'),inspector=make('aside','desk-inspector');
 shell.setAttribute('aria-label','Creator workspace');rail.setAttribute('aria-label','Workspace shortcuts');library.setAttribute('aria-label','Workspace library');canvas.setAttribute('aria-label','AI and terminal workspace');inspector.setAttribute('aria-label','Workspace details');
 shell.append(rail,library,canvas);wrap.prepend(shell);
 rail.innerHTML='<div class="desk-identity"><span class="desk-avatar" id="deskAvatar">N</span><div><strong id="deskUser">Your workspace</strong><small id="deskAccount">On this device</small></div></div><nav class="desk-nav" aria-label="Workspace tools"><button data-desk-open="workspace" aria-current="page"><span aria-hidden="true">▦</span><b>Workspace</b></button><button data-desk-open="projects"><span aria-hidden="true">◈</span><b>Projects</b><small id="deskProjectCount">0</small></button><button data-desk-open="ai"><span aria-hidden="true">✳</span><b>Coin AI</b></button><button data-desk-open="terminal"><span aria-hidden="true">&gt;_</span><b>Terminal</b></button><button data-desk-open="servers"><span aria-hidden="true">▤</span><b>Servers</b></button><button data-desk-open="connections"><span aria-hidden="true">⌁</span><b>Connections</b></button></nav><div class="desk-rail-links"><a href="studio.html">Studio ↗</a><a href="launchpad.html">Coin desk ↗</a><a href="explorer.html">Explore ↗</a><a href="billing.html">Account ↗</a></div><div class="desk-rail-bottom"><button id="deskCommands" type="button"><span>Find an action</span><kbd>⌘ K</kbd></button><button id="deskMotion" type="button" aria-pressed="false">Motion on <span aria-hidden="true">◌</span></button><button id="deskSettings" type="button">Personalize ↗</button></div>';
 q('deskCommands').querySelector('kbd').textContent=/Mac/i.test(navigator.platform)?'⌘ K':'Ctrl K';
 library.innerHTML='<header class="desk-library-head"><div><span>YOUR WORK</span><h2>Workspaces</h2></div><button type="button" id="deskNewProject" aria-label="Create a new project">＋</button></header><label class="desk-search"><span aria-hidden="true">⌕</span><input type="search" id="deskSearch" placeholder="Search your work" aria-label="Search workspace library"><kbd>/</kbd></label><div class="desk-filters" role="group" aria-label="Workspace list"><button data-desk-list="projects" aria-pressed="true">Projects</button><button data-desk-list="servers" aria-pressed="false">Servers</button><button data-desk-list="coins" aria-pressed="false">Coins</button></div><div class="desk-library-tools"><small id="deskListCount">0 projects</small><button id="deskArchived" type="button" aria-pressed="false">Archived</button></div><div id="deskCards" class="desk-cards"></div><p id="deskListStatus" class="desk-note" role="status"></p><div class="desk-library-foot"><button id="deskExport" type="button">Export ↓</button><button id="deskImport" type="button">Import ↑</button></div>';
 const heading=wrap.querySelector('.account-heading');heading.classList.add('desk-canvas-heading');heading.querySelector('h1').textContent='Your next thing starts here.';heading.querySelector('h1').setAttribute('aria-label','Your creator workspace');heading.querySelector('p').textContent='A purpose. A little intelligence. A place to build.';const manageButton=make('button','desk-manage-button','Manage workspace ↗');manageButton.type='button';manageButton.addEventListener('click',()=>showManager('projects'));heading.querySelector('a').replaceWith(manageButton);canvas.append(heading);
 const summary=wrap.querySelector('.account-summary');summary.classList.add('desk-summary');canvas.append(summary);
 const work=make('div','desk-work');work.id='deskWork';canvas.append(work);
 const chatSelectors=make('div','desk-chat-selectors');const chat=q('aiChat');if(chat){const labels=[...chat.querySelectorAll('.ai-workspace-select,.ai-model-label')];if(labels.length){labels[0].before(chatSelectors);chatSelectors.append(...labels);}}
 const ai=grid.querySelector('.dev-module-ai'),terminal=grid.querySelector('.dev-module-terminal');if(ai)work.append(ai);if(terminal){work.append(terminal);terminal.querySelectorAll('.cli-unlock-copy h2 br').forEach(br=>br.replaceWith(document.createTextNode(' ')));}
 inspector.innerHTML='<header class="desk-inspector-head"><div><span>THE NEXT DETAIL</span><h2>Make it happen.</h2></div><span class="desk-detail-mark" aria-hidden="true">↘</span></header>';
 const project=make('details','desk-detail');project.id='deskProjectDetails';project.open=true;project.innerHTML='<summary>Project brief · this device <span>↗</span></summary><div class="desk-detail-body"><div id="deskBriefEmpty" class="desk-empty"><strong>Start with a useful idea.</strong><p>Create a project, or import your saved library. Your first milestone starts here.</p><a href="studio.html?project=new#brief">Write your brief ↗</a></div><form id="deskBriefForm" hidden><label>PROJECT<input id="deskBriefName" maxlength="80" required></label><label>PURPOSE<textarea id="deskBriefPurpose" maxlength="500" rows="3" required></textarea></label><div class="desk-detail-actions"><button type="submit">Save changes ↗</button><a id="deskBriefStudio" href="studio.html">Open Studio ↗</a><button id="deskArchiveProject" type="button">Archive</button></div></form><div id="deskMilestones" hidden><div class="desk-progress-head"><strong>Next steps</strong><small id="deskTaskCount"></small></div><progress id="deskProgress" max="100" value="0" aria-label="Project milestone progress"></progress><div id="deskTasks"></div><form id="deskTaskForm" class="desk-task-compose"><input id="deskTaskInput" maxlength="160" placeholder="Add a milestone" aria-label="New project milestone" required><button type="submit" aria-label="Add milestone">＋</button></form></div><p id="deskBriefStatus" class="desk-note" role="status"></p></div>';inspector.append(project);
 const manager=make('aside','desk-manager');manager.id='deskManager';manager.setAttribute('aria-labelledby','deskManagerTitle');manager.innerHTML='<header class="desk-manager-head"><div><span class="kicker">WORKSPACE DETAILS</span><h2 id="deskManagerTitle">Your projects.</h2><p id="deskManagerCopy">Your brief and next steps.</p></div><button type="button" id="deskCloseManager" aria-label="Return to project details">×</button></header><label class="desk-detail-select"><span class="desk-sr-status">Inspect workspace</span><select id="deskDetailSelect" aria-label="Inspect workspace"><option value="projects">Project brief</option><option value="servers">Servers</option><option value="coins">Coin knowledge</option><option value="connections">Connections</option><option value="credits">Credits</option><option value="tools">More tools</option></select></label><div class="desk-inspector-actions"><button type="button" id="deskResetBrief">Cancel</button><button type="submit" form="deskBriefForm" id="deskSaveBrief">Save changes ↗</button></div>';
 const milestoneLabel=make('label','','NEXT MILESTONE'),milestoneInput=make('input');milestoneInput.id='deskBriefMilestone';milestoneInput.maxLength=160;milestoneLabel.append(milestoneInput);project.querySelector('#deskBriefPurpose').closest('label').after(milestoneLabel);
 const managerBody=make('div','desk-manager-body');managerBody.append(inspector);manager.append(managerBody);shell.append(manager);inspector.querySelector('.desk-inspector-head').remove();
 const managerGroups={projects:['deskProjectDetails'],servers:['deskServers','deskServerPlan'],coins:['deskCoinInspector'],connections:['deskConnections'],credits:['deskCredits'],tools:['deskJupiter','deskWatchlist','deskTools','deskActivity']};
 const managerCopy={projects:['Your projects.','Your brief and next steps, saved on this device.'],servers:['Your places to build.','Choose a workspace, inspect the fleet and manage your server.'],coins:['A growing purpose.','Your coin context, saved knowledge and local AI tools.'],connections:['Connected to your work.','Wallets, GitHub and creator payout plans.'],credits:['Room for what comes next.','Your AI and server balances, with account funding tools.'],tools:['A few useful things.','Jupiter tools, saved markets, shortcuts and this session.']};
 function showManager(kind='projects',target=null){
  const group=managerGroups[kind]||managerGroups.projects;manager.dataset.kind=kind;if(['projects','servers','coins'].includes(kind)&&listKind!==kind)setList(kind);
  for(const d of inspector.querySelectorAll(':scope > .desk-detail')){d.hidden=!group.includes(d.id);if(!d.hidden)d.open=kind!=='tools'||d.id==='deskJupiter';}
  const copy=managerCopy[kind]||managerCopy.projects;q('deskManagerTitle').textContent=copy[0];q('deskManagerCopy').textContent=copy[1];q('deskDetailSelect').value=kind;q('deskResetBrief').parentElement.hidden=kind!=='projects';
  const detail=target||q(group[0]);if(detail?.tagName==='DETAILS')detail.open=true;if(target)target.scrollIntoView({block:'nearest',behavior:'instant'});else{managerBody.scrollTop=0;inspector.scrollTop=0;}
  if(innerWidth<1000)manager.scrollIntoView({block:'start',behavior:reduce.matches||paused?'instant':'smooth'});
 }
 q('deskCloseManager').addEventListener('click',()=>showManager('projects'));q('deskDetailSelect').addEventListener('change',e=>showManager(e.target.value));q('deskResetBrief').addEventListener('click',()=>{document.activeElement.blur();renderBrief();q('deskBriefStatus').textContent='Unsaved changes cleared.';});
 const sections={workspace:heading,projects:library,ai,terminal};
 function detail(content,title,id,open=false){if(!content)return;const d=make('details','desk-detail');d.id=id;d.open=open;const s=make('summary','',title);s.append(make('span','','＋'));const body=make('div','desk-detail-body');body.append(content);d.append(s,body);inspector.append(d);sections[id]=d;return d;}
 // Mirror the original authenticated gate when moving coin controls into the inspector.
 const aiGrid=q('aiWorkspace')?.querySelector('.ai-grid');
 if(aiGrid){const host=make('div','desk-coin-details');host.id='deskCoinDetails';for(const d of [...aiGrid.querySelectorAll('.dev-ai-details')])host.append(d);q('aiWorkspace').append(host);}
 const coinJump=make('details','desk-detail');coinJump.id='deskCoinInspector';coinJump.innerHTML='<summary>Coin context + knowledge <span>＋</span></summary><div class="desk-detail-body"><p class="desk-note">Choose your coin in the workspace list. Edit its private context and knowledge alongside the chat.</p><button type="button" id="deskEditCoin">Open coin context ↗</button></div>';inspector.append(coinJump);const coinHost=q('deskCoinDetails');if(coinHost){coinJump.querySelector('.desk-detail-body').append(coinHost);const syncGate=()=>{coinHost.hidden=q('aiWorkspace').hidden;coinJump.querySelector('p').hidden=!coinHost.hidden;};new MutationObserver(syncGate).observe(q('aiWorkspace'),{attributes:true,attributeFilter:['hidden']});syncGate();}
 const servers=detail(grid.querySelector('.dev-module-servers'),'Server fleet','deskServers',true);sections.servers=servers;
 const plan=wrap.querySelector('.account-workspace-grid');detail(plan,'Selected server plan','deskServerPlan');
 const connections=grid.querySelector('#connections');sections.connections=detail(connections,'Connections + payouts','deskConnections');
 detail(wrap.querySelector('.account-watch-section'),'Saved market watch','deskWatchlist');detail(wrap.querySelector('.account-next-section'),'Tools + shortcuts','deskTools');
 detail(grid.querySelector('#credits'),'AI + server credits','deskCredits');detail(grid.querySelector('#jupiterWorkspace'),'Jupiter tools','deskJupiter');
 const activity=make('details','desk-detail');activity.id='deskActivity';activity.innerHTML='<summary>This session <span>＋</span></summary><div class="desk-detail-body"><ol id="deskActivityRows" class="desk-activity"></ol><p id="deskActivityEmpty" class="desk-note">Updates appear here as you work. No previous activity is inferred.</p></div>';inspector.append(activity);
 const extras=wrap.querySelector('.dev-dashboard-extras');if(extras){extras.classList.add('desk-extra-storage');const librarySection=extras.querySelector('#projects');if(librarySection){const disclosure=librarySection.closest('details');disclosure.open=true;disclosure.querySelector('summary').textContent='Project library and backups';}canvas.append(extras);}
 grid.remove();
 let listKind='projects',archived=false,paused=false,recordedWallet='',lastRuntime=null,lastProject=null;
 const reduce=matchMedia('(prefers-reduced-motion: reduce)'),announcer=make('p','desk-sr-status');announcer.setAttribute('role','status');announcer.setAttribute('aria-live','polite');shell.append(announcer);
 function tell(text){announcer.textContent=text;q('deskListStatus').textContent=text;}
 function pulse(element){if(!element||reduce.matches||paused)return;element.animate([{outlineColor:'#ff91bd80'},{outlineColor:'#ff91bd00'}],{duration:650});}
 function log(message){const rows=q('deskActivityRows'),li=make('li');li.append(make('time','',new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})),make('span','',message));rows.prepend(li);while(rows.children.length>20)rows.lastChild.remove();q('deskActivityEmpty').hidden=true;}
 const originalStatus=q('libraryStatus');if(originalStatus)new MutationObserver(()=>{if(originalStatus.textContent)tell(originalStatus.textContent);}).observe(originalStatus,{childList:true,characterData:true,subtree:true});
 function projectRows(){return window.NUC_PROJECTS?.list()||[];}
 function renderBrief(){const p=window.NUC_PROJECTS?.active(),present=!!p;q('deskBriefEmpty').hidden=present;q('deskBriefForm').hidden=!present;q('deskMilestones').hidden=!present;q('deskProjectCount').textContent=projectRows().filter(p=>!p.archived).length;
  q('deskSaveBrief').disabled=!present;if(!p)return;const fields=p.draft.fields;if(!q('deskBriefForm').contains(document.activeElement)){q('deskBriefName').value=fields.name;q('deskBriefPurpose').value=fields.purpose;q('deskBriefMilestone').value=fields.milestone;}
  q('deskBriefStudio').href='studio.html?project='+encodeURIComponent(p.id)+'#brief';const done=p.tasks.filter(t=>t.done).length;q('deskTaskCount').textContent=done+' / '+p.tasks.length;q('deskProgress').value=p.tasks.length?done/p.tasks.length*100:0;
  q('deskTasks').replaceChildren();for(const task of p.tasks){const label=make('label','desk-task'),box=make('input');box.type='checkbox';box.checked=task.done;box.setAttribute('aria-label',task.title);const title=make('span','',task.title);label.append(box,title);box.addEventListener('change',()=>{try{window.NUC_PROJECTS.toggleTask(p.id,task.id,box.checked);log((box.checked?'Completed: ':'Reopened: ')+task.title);}catch(e){box.checked=!box.checked;q('deskBriefStatus').textContent=e.message;}});q('deskTasks').append(label);}
 }
 function getRows(){if(listKind==='servers')return (window.NUC_DEV_RUNTIME?.list()||[]).filter(w=>w.server&&w.canManageServer).map(w=>({id:w.id,name:w.project,description:(w.server.nodeName||'Pi')+' · '+w.server.status,meta:'WEBSITE SERVER',selected:window.NUC_DEV_RUNTIME.selected()===w.id,raw:w}));if(listKind==='coins')return (window.NUC_COIN_WORKSPACES?.list()||[]).map(c=>({id:c.id,name:c.name,description:c.story||'Private coin AI workspace',meta:c.ticker+' · COIN AI',selected:window.NUC_COIN_WORKSPACES.selected()===c.id,raw:c}));return projectRows().filter(p=>p.archived===archived).map(p=>({id:p.id,name:p.draft.fields.name,description:p.draft.fields.purpose,meta:p.draft.fields.workload.toUpperCase()+' · '+p.tasks.filter(t=>t.done).length+'/'+p.tasks.length+' STEPS',selected:window.NUC_PROJECTS.active()?.id===p.id,raw:p}));}
 async function choose(row){try{if(listKind==='projects'){if(archived){window.NUC_PROJECTS.setArchived(row.id,false);archived=false;tell('Project restored.');}window.NUC_PROJECTS.select(row.id);project.open=true;lastProject=row.id;log('Selected project: '+row.name);}else if(listKind==='servers'){window.NUC_DEV_RUNTIME.select(row.id);q('deskServerPlan').open=true;open('terminal');}else{await window.NUC_COIN_WORKSPACES.select(row.id);coinJump.open=true;open('ai');}
  const h=heading.querySelector('h1');h.textContent=row.name;renderList();pulse(q('deskCards').querySelector('[aria-pressed="true"]'));}catch(e){tell(e.message);}}
 function renderList(){const query=q('deskSearch').value.trim().toLowerCase(),rows=getRows().filter(r=>(r.name+' '+r.description+' '+r.meta).toLowerCase().includes(query)),cards=q('deskCards');cards.replaceChildren();q('deskListCount').textContent=rows.length+' '+listKind+(listKind==='projects'?' · this device':'');q('deskArchived').hidden=listKind!=='projects';q('deskArchived').setAttribute('aria-pressed',String(archived));q('deskExport').disabled=projectRows().length===0;
  for(const row of rows){const button=make('button','desk-work-card');button.type='button';button.dataset.workspaceId=row.id;button.setAttribute('aria-pressed',String(row.selected));const top=make('div','desk-card-top');top.append(make('span','desk-card-avatar',row.name.trim().slice(0,1).toUpperCase()),make('strong','',row.name));const status=make('small','desk-card-meta',row.meta),description=make('p','',row.description);button.append(top,status,description);button.addEventListener('click',()=>choose(row));cards.append(button);}
  if(!rows.length){const empty=make('div','desk-empty');empty.append(make('strong','',query?'Nothing matched.':listKind==='projects'?'A useful idea starts here.':listKind==='servers'?'Your next place to build.':'A little intelligence.'),make('p','',query?'Try another name or clear the search.':listKind==='projects'?'Write a brief or import your library. Your projects and milestones will appear here.':window.NUC_BILLING?.state.user?listKind==='servers'?'Create a Free website workspace to connect its terminal.':'Create a private coin workspace to start chatting.':'Sign in on the Pi website to see your private workspaces.'));const link=make('a','',listKind==='projects'?'Create a project ↗':listKind==='servers'?'Open account ↗':'Create coin AI ↗');link.href=listKind==='projects'?'studio.html?project=new#brief':listKind==='servers'?'billing.html':'#coinAI';if(listKind==='coins')link.addEventListener('click',()=>{coinJump.open=true;q('deskCoinDetails')?.querySelector('details')?.setAttribute('open','');q('aiCreateDetails').open=true;open(window.NUC_BILLING?.state.user?'deskCoinInspector':'ai');});empty.append(link);cards.append(empty);}
 }
 function setList(kind){listKind=kind;library.querySelector('.desk-library-head h2').textContent={projects:'Projects',servers:'Servers',coins:'Coin AI'}[kind];q('deskNewProject').setAttribute('aria-label',{projects:'Create a new project',servers:'Create a server workspace',coins:'Create a coin AI workspace'}[kind]);library.querySelector('.desk-library-foot').hidden=kind!=='projects';q('deskSearch').value='';q('deskListStatus').textContent='';library.querySelectorAll('[data-desk-list]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.deskList===kind)));renderList();}
 function open(id){
  if(id==='coinAI'||id==='aiChat')id='ai';
  const target=sections[id]||q(id);if(!target)return;
  const group=Object.keys(managerGroups).find(key=>managerGroups[key].some(detailId=>q(detailId)?.contains(target)));
  if(id==='projects')showManager('projects');else if(group)showManager(group,target);
  if(target.tagName==='DETAILS')target.open=true;for(let p=target.parentElement;p&&p!==document.body;p=p.parentElement)if(p.tagName==='DETAILS')p.open=true;
  if(id==='terminal'||id==='ai'||id==='workspace')focusTool(id==='terminal'?'terminal':'ai');
  if(id==='projects')managerBody.scrollTop=0;else target.scrollIntoView({behavior:reduce.matches||paused?'instant':'smooth',block:'nearest'});
  if(id==='terminal'&&!q('cliCommand').disabled)q('cliCommand').focus({preventScroll:true});if(id==='ai'&&!q('aiQuestion').disabled)q('aiQuestion').focus({preventScroll:true});rail.querySelectorAll('[data-desk-open]').forEach(b=>b.dataset.deskOpen===id?b.setAttribute('aria-current','page'):b.removeAttribute('aria-current'));pulse(target);
 }
 window.NUC_DEV_PANELS={open};if(window.NUC_CONNECTIONS)window.NUC_CONNECTIONS.open=()=>open('connections');
 rail.querySelectorAll('[data-desk-open]').forEach(button=>{button.setAttribute('aria-label',button.querySelector('b').textContent);button.addEventListener('click',()=>{if(button.dataset.deskOpen==='projects')setList('projects');if(button.dataset.deskOpen==='servers')setList('servers');open(button.dataset.deskOpen);});});
 library.querySelectorAll('[data-desk-list]').forEach(b=>b.addEventListener('click',()=>showManager(b.dataset.deskList)));q('deskSearch').addEventListener('input',renderList);q('deskArchived').addEventListener('click',()=>{archived=!archived;renderList();});
 q('deskNewProject').addEventListener('click',()=>{if(listKind==='projects')q('newProject').click();else if(listKind==='servers')location.href='billing.html';else if(window.NUC_BILLING?.state.user){showManager('coins');q('deskCoinDetails')?.querySelector('details')?.setAttribute('open','');q('aiCreateDetails').open=true;q('aiName').focus();}else open('ai');});q('deskExport').addEventListener('click',()=>q('exportProjects').click());q('deskImport').addEventListener('click',()=>q('importProjects').click());
 q('deskBriefForm').addEventListener('submit',e=>{e.preventDefault();const p=window.NUC_PROJECTS.active();if(!p)return;const draft=structuredClone(p.draft);draft.fields.name=q('deskBriefName').value.trim();draft.fields.purpose=q('deskBriefPurpose').value.trim();draft.fields.milestone=q('deskBriefMilestone').value.trim();const result=window.NUC_PROJECTS.saveDraft(draft);if(!result.ok){q('deskBriefStatus').textContent=result.error;return;}try{window.NUC_PROJECTS.select(result.project.id);q('deskBriefStatus').textContent='Brief saved on this device.';heading.querySelector('h1').textContent=draft.fields.name;log('Updated project brief.');}catch(error){q('deskBriefStatus').textContent=error.message;}});
 q('deskArchiveProject').addEventListener('click',()=>{try{const p=window.NUC_PROJECTS.active();if(p){window.NUC_PROJECTS.setArchived(p.id,true);heading.querySelector('h1').textContent='Your next thing starts here.';tell('Project archived. Use Archived to restore it.');log('Archived project: '+p.draft.fields.name);}}catch(error){q('deskBriefStatus').textContent=error.message;}});
 q('deskTaskForm').addEventListener('submit',e=>{e.preventDefault();try{const p=window.NUC_PROJECTS.active();window.NUC_PROJECTS.addTask(p.id,q('deskTaskInput').value);log('Added milestone: '+q('deskTaskInput').value.trim());q('deskTaskInput').value='';q('deskBriefStatus').textContent='Milestone saved.';}catch(error){q('deskBriefStatus').textContent=error.message;}});
 q('deskEditCoin').addEventListener('click',()=>{showManager('coins');coinJump.open=true;const d=q('deskCoinDetails')?.querySelector('details');if(d){d.open=true;d.scrollIntoView({block:'nearest',behavior:reduce.matches?'instant':'smooth'});}});
 function panelRoom(panel,key){if(!panel)return;const host=panel.querySelector(key==='ai'?'.ai-heading':'.cli-header-controls');if(!host)return;const button=make('button','desk-panel-room','↗');button.type='button';button.setAttribute('aria-label','Give '+(key==='ai'?'AI':'terminal')+' more room');button.setAttribute('aria-pressed','false');host.append(button);button.addEventListener('click',()=>{work.dataset.focus=work.dataset.focus===key?'':key;work.querySelectorAll('.desk-panel-room').forEach(b=>b.setAttribute('aria-pressed',String(b===button&&work.dataset.focus===key)));});}
 panelRoom(ai,'ai');panelRoom(terminal,'terminal');
 const dialog=make('dialog','desk-command-dialog');dialog.id='deskCommandPalette';dialog.setAttribute('aria-labelledby','deskCommandTitle');dialog.innerHTML='<header><strong id="deskCommandTitle">What would you like to do?</strong><button type="button" id="deskClosePalette" aria-label="Close command palette">×</button></header><label class="desk-search"><span aria-hidden="true">⌕</span><input id="deskCommandSearch" type="search" placeholder="Search actions…" aria-label="Search workspace actions"></label><div id="deskCommandResults"></div><footer>↑ ↓ move · Enter choose · Esc close</footer>';document.body.append(dialog);let returnFocus=null,commandIndex=0,restoreOnClose=true;
 const commands=[['Open terminal','terminal',()=>open('terminal')],['Chat with local AI','AI',()=>open('ai')],['Find a project','projects',()=>{setList('projects');open('projects');q('deskSearch').focus();}],['View server workspaces','servers',()=>showManager('servers')],['Connect a wallet','wallet',()=>window.NUC_WALLET?.open()],['Creator GitHub and payouts','connections',()=>open('connections')],['View AI and server credits','credits',()=>open('deskCredits')],['Use Jupiter tools','Jupiter',()=>open('deskJupiter')],['Create a project','new',()=>q('newProject').click()],['Export project backup','backup',()=>q('exportProjects').click()],['Import project backup','backup',()=>q('importProjects').click()],['Personalize workspace','settings',()=>q('workspaceSettings').showModal()]];
 function renderCommands(){const query=q('deskCommandSearch').value.toLowerCase(),results=q('deskCommandResults');results.replaceChildren();commandIndex=0;for(const [label,keywords,action] of commands.filter(c=>(c[0]+' '+c[1]).toLowerCase().includes(query))){const b=make('button','desk-command-result');b.type='button';b.append(make('span','',label),make('small','','↗'));b.addEventListener('click',()=>{restoreOnClose=false;dialog.close();action();});results.append(b);}if(!results.children.length)results.append(make('p','desk-note','No actions match that search.'));markCommand();}
 function markCommand(){const buttons=[...q('deskCommandResults').querySelectorAll('button')];buttons.forEach((b,i)=>b.classList.toggle('is-current',i===commandIndex));buttons[commandIndex]?.scrollIntoView({block:'nearest'});}
 function palette(){if(dialog.open){dialog.close();return;}returnFocus=document.activeElement;restoreOnClose=true;q('deskCommandSearch').value='';renderCommands();dialog.showModal();q('deskCommandSearch').focus();}
 q('deskCommands').addEventListener('click',palette);q('deskClosePalette').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{if(restoreOnClose)returnFocus?.focus({preventScroll:true});});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});q('deskCommandSearch').addEventListener('input',renderCommands);dialog.addEventListener('keydown',e=>{const buttons=[...q('deskCommandResults').querySelectorAll('button')];if(['ArrowDown','ArrowUp','Enter'].includes(e.key)&&buttons.length){e.preventDefault();if(e.key==='Enter')buttons[commandIndex].click();else{commandIndex=(commandIndex+(e.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length;markCommand();}}});
 document.addEventListener('keydown',e=>{const typing=e.target.closest('input,textarea,select,[contenteditable="true"]');if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();e.stopImmediatePropagation();palette();}else if(e.key==='/'&&!typing&&!e.ctrlKey&&!e.metaKey&&!dialog.open){e.preventDefault();showManager('projects');q('deskSearch').focus();}else if(e.altKey&&!e.ctrlKey&&!e.metaKey&&['1','2','3'].includes(e.key)){e.preventDefault();open({'1':'terminal','2':'ai','3':'projects'}[e.key]);}},true);
 q('deskSettings').addEventListener('click',()=>q('workspaceSettings').showModal());
 inspector.querySelectorAll('details').forEach(d=>d.addEventListener('toggle',()=>{if(d.open&&!reduce.matches&&!paused){d.querySelector(':scope > div')?.animate([{opacity:.45,transform:'translateY(-4px)'},{opacity:1,transform:'translateY(0)'}],{duration:180,easing:'ease-out'});}}));
 function motion(){document.body.classList.toggle('desk-still',paused||reduce.matches);q('deskMotion').setAttribute('aria-pressed',String(paused));q('deskMotion').disabled=reduce.matches;q('deskMotion').textContent=reduce.matches?'Motion reduced':paused?'Motion paused Ⅱ':'Motion on ◌';}
 q('deskMotion').addEventListener('click',()=>{paused=!paused;window.NUC_DOTS?.setPaused(paused);motion();});reduce.addEventListener('change',motion);
 window.addEventListener('nucProjectsChange',()=>{renderBrief();renderList();});window.addEventListener('nuc-ai-workspaces',()=>{if(listKind==='coins')renderList();});window.addEventListener('nuc-runtime-change',()=>{const selected=window.NUC_DEV_RUNTIME?.selected();if(selected&&lastRuntime&&selected!==lastRuntime)log('Selected server workspace.');lastRuntime=selected;if(listKind==='servers')renderList();});
 window.addEventListener('nuc-wallet-change',e=>{const s=e.detail,key=[s.connected,s.address,s.verified].join(':');if(recordedWallet&&key!==recordedWallet)log(s.verified?'Wallet account link verified.':s.connected?'Wallet connected.':'Wallet disconnected.');recordedWallet=key;});
 window.addEventListener('hashchange',()=>open(location.hash.slice(1)));window.NUC_BILLING?.ready.then(s=>{if(s.user){q('deskUser').textContent=s.user.name||'Your workspace';q('deskAccount').textContent='Private account';q('deskAvatar').textContent=(s.user.name||'N').trim().slice(0,1).toUpperCase();}else q('deskAccount').textContent=location.hostname.endsWith('.github.io')?'Public preview':'On this device';renderList();});
 const aiHeading=ai?.querySelector('.ai-heading h2');if(aiHeading)aiHeading.textContent='A little intelligence.';
 if(q('aiChatTitle')){const addCoin=make('button','desk-add-coin','New coin ＋');addCoin.type='button';addCoin.addEventListener('click',()=>{coinJump.open=true;q('deskCoinDetails')?.querySelector('details')?.setAttribute('open','');q('aiCreateDetails').open=true;open(window.NUC_BILLING?.state.user?'deskCoinInspector':'ai');if(window.NUC_BILLING?.state.user)q('aiName').focus();});ai.querySelector('.ai-heading').append(addCoin);}
 ai?.addEventListener('click',e=>{if(e.target.closest('.ai-message-assistant .ai-button')){showManager('coins');const details=q('deskCoinDetails')?.querySelectorAll('details');details?.forEach(d=>d.open=true);q('aiKnowledgeText')?.focus({preventScroll:true});q('aiKnowledgeText')?.scrollIntoView({block:'center',behavior:reduce.matches||paused?'instant':'smooth'});}});
 const toolbar=make('div','desk-conversation-tools');toolbar.innerHTML='<div class="desk-tool-actions"><button type="button" id="deskQuickNew" aria-label="New project"></button><button type="button" id="deskQuickExport" aria-label="Export project backup"></button><button type="button" id="deskQuickKnowledge" aria-label="Open coin knowledge"></button><button type="button" id="deskQuickConnections" aria-label="Open connections"></button></div><div class="desk-tool-tabs" role="group" aria-label="Workspace focus"><button type="button" data-desk-focus="ai" aria-pressed="true">Chat</button><button type="button" data-desk-focus="terminal" aria-pressed="false">Terminal</button></div>';canvas.prepend(toolbar);
 function focusTool(kind){work.dataset.focus=kind==='terminal'?'terminal':'';toolbar.querySelectorAll('[data-desk-focus]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.deskFocus===kind)));work.querySelectorAll('.desk-panel-room').forEach(b=>b.setAttribute('aria-pressed',String(kind==='terminal'&&terminal?.contains(b))));}
 toolbar.querySelectorAll('[data-desk-focus]').forEach(b=>b.addEventListener('click',()=>open(b.dataset.deskFocus)));
 q('deskQuickNew').addEventListener('click',()=>q('newProject').click());q('deskQuickExport').addEventListener('click',()=>q('exportProjects').click());q('deskQuickKnowledge').addEventListener('click',()=>showManager('coins'));q('deskQuickConnections').addEventListener('click',()=>showManager('connections'));
 terminal?.querySelector('.cli-header')?.addEventListener('click',e=>{if(!e.target.closest('button,select'))open('terminal');});work.querySelectorAll('.desk-panel-room').forEach(b=>b.addEventListener('click',()=>focusTool(terminal?.contains(b)?'terminal':'ai')));
 const icon=(paths)=>'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.45" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+paths+'</svg>';
 const icons={workspace:'<rect x="4" y="4" width="6" height="6" rx="1.5"/><rect x="14" y="4" width="6" height="6" rx="1.5"/><rect x="4" y="14" width="6" height="6" rx="1.5"/><rect x="14" y="14" width="6" height="6" rx="1.5"/>',projects:'<path d="M4 7a2 2 0 0 1 2-2h5l2 3h5a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2Z"/>',ai:'<path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5Z"/>',terminal:'<path d="m5 7 5 5-5 5m8 0h6"/>',servers:'<rect x="4" y="3" width="16" height="8" rx="2"/><rect x="4" y="13" width="16" height="8" rx="2"/><path d="M8 7h.01M8 17h.01m5-10h4m-4 10h4"/>',connections:'<path d="m9 15 6-6M8 17l-1 1a4 4 0 0 1-6-6l4-4a4 4 0 0 1 6 0m2 8a4 4 0 0 0 6 0l4-4a4 4 0 0 0-6-6l-1 1"/>',new:'<path d="M12 5v14M5 12h14"/>',export:'<path d="M5 14v5h14v-5m-7-11v11m-4-4 4 4 4-4"/>',knowledge:'<path d="M5 4h12a2 2 0 0 1 2 2v14H7a2 2 0 0 1-2-2Zm0 12h14M9 8h6m-6 4h5"/>'};
 rail.querySelectorAll('[data-desk-open] > span').forEach(n=>n.innerHTML=icon(icons[n.parentElement.dataset.deskOpen]));q('deskQuickNew').innerHTML=icon(icons.new);q('deskQuickExport').innerHTML=icon(icons.export);q('deskQuickKnowledge').innerHTML=icon(icons.knowledge);q('deskQuickConnections').innerHTML=icon(icons.connections);
 const identityAccount=make('a','desk-identity-account');identityAccount.href='billing.html';identityAccount.setAttribute('aria-label','Account and sign in');identityAccount.innerHTML=icon('<path d="M8 18a4 4 0 0 0 8 0M6 15h12l-1-3V8a5 5 0 0 0-10 0v4Z"/>');rail.querySelector('.desk-identity').append(identityAccount);
 const compose=make('button','desk-compose');compose.type='button';compose.setAttribute('aria-label','Create a project');compose.innerHTML=icon('<path d="m14 5 5 5m-2-7 4 4-11 11-6 2 2-6Z"/>');compose.addEventListener('click',()=>q('newProject').click());rail.querySelector('.desk-identity').append(compose);
 const selected=window.NUC_PROJECTS?.active();if(selected){heading.querySelector('h1').textContent=selected.draft.fields.name;lastProject=selected.id;}renderBrief();renderList();showManager('projects');motion();
 if(location.hash)requestAnimationFrame(()=>open(location.hash.slice(1)));
})();
