const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const fixture=require('./dashboard-fixtures.cjs');const base=process.env.REVIEW_BASE_URL||'http://127.0.0.1:8097',out=process.env.REVIEW_OUTPUT||path.resolve(__dirname,'../../docs/dashboard-review');
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true,...(process.env.REVIEW_BROWSER?{executablePath:process.env.REVIEW_BROWSER}:{})});const ctx=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),p=await ctx.newPage(),checks=[],errors=[],assets=[];
p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.url().startsWith(base)&&/\.(js|css|svg|ttf|woff2?)(\?|$)/.test(r.url())&&r.status()>=400)assets.push(r.url());});const check=(name,passed)=>{checks.push({name,passed:!!passed});assert.ok(passed,name);console.log('PASS',name);};const goto=()=>p.goto(base+'/dashboard.html');
try{
await goto();await p.waitForFunction(()=>window.NUC_DESK_VIEW);check('empty overview shows only real local counts',await p.locator('#atelierProjectCount').innerText()==='00'&&await p.locator('#atelierMilestoneCount').innerText()==='00 / 00'&&await p.locator('.desk-work-card').count()===0);
check('private AI stays behind its account gate',await p.locator('#aiGate').isVisible()&&!await p.locator('#aiWorkspace').isVisible()&&!await p.locator('#deskCoinDetails').isVisible());
await p.locator('#atelierNewProject').click();await p.locator('#deskBriefName').fill('Studio North');await p.locator('#deskBriefPurpose').fill('Useful research tools for people who make things.');await p.locator('#deskBriefMilestone').fill('Publish the first page');await p.locator('#deskSaveBrief').click();check('project can be created entirely inside the redesigned dashboard',await p.evaluate(()=>NUC_PROJECTS.active()?.draft.fields.name==='Studio North')&&await p.locator('#atelierProjectCount').innerText()==='01');
await p.locator('#deskBriefPurpose').fill('A better purpose, not yet saved');await p.locator('[data-atelier-context=library]').click();await p.locator('[data-atelier-context=details]').click();check('changing context preserves unsaved brief edits',await p.locator('#deskBriefPurpose').inputValue()==='A better purpose, not yet saved');await p.locator('#deskResetBrief').click();check('Cancel restores the saved brief',await p.locator('#deskBriefPurpose').inputValue()==='Useful research tools for people who make things.');
await p.locator('#deskTaskInput').fill('Invite the first researcher');await p.locator('#deskTaskForm button').click();await p.locator('.desk-task input').first().check();check('milestones update overview from actual saved tasks',await p.locator('#atelierMilestoneCount').innerText()==='01 / 02'&&await p.evaluate(()=>NUC_PROJECTS.active().tasks[0].done));
await p.reload();await p.waitForFunction(()=>window.NUC_DESK_VIEW);check('project and milestone counts persist through reload',await p.locator('#atelierProjectCount').innerText()==='01'&&await p.locator('#atelierMilestoneCount').innerText()==='01 / 02');
await p.locator('#atelierNewProject').click();await p.locator('#deskBriefName').fill('Second project');await p.locator('#deskBriefPurpose').fill('Keep the first project intact.');await p.locator('#deskSaveBrief').click();check('new project preserves the existing library',await p.evaluate(()=>NUC_PROJECTS.list().length===2));await p.locator('#deskCloseManager').click();check('Back returns to the library with visible keyboard focus',await p.locator('.desk-library').isVisible()&&await p.locator('[data-atelier-context=library]').evaluate(e=>e===document.activeElement));
await p.locator('#deskSearch').fill('North');check('library search finds the actual saved project',await p.locator('.desk-work-card').count()===1&&(await p.locator('.desk-work-card').innerText()).includes('Studio North'));await p.locator('.desk-work-card').click();check('selecting a project opens its details',await p.locator('#deskBriefName').inputValue()==='Studio North'&&await p.locator('#deskManager').isVisible());await p.locator('#deskArchiveProject').click();await p.locator('[data-atelier-context=library]').click();await p.locator('#deskArchived').click();await p.locator('.desk-work-card').click();check('archived projects can be restored intact',await p.evaluate(()=>NUC_PROJECTS.active().draft.fields.name==='Studio North'&&!NUC_PROJECTS.active().archived&&NUC_PROJECTS.active().tasks[0].done));
await p.locator('#atelierBackup').click({trial:true});const event=p.waitForEvent('download');await p.locator('#atelierBackup').click();const download=await event,backup=JSON.parse(fs.readFileSync(await download.path(),'utf8'));check('visible backup action exports complete projects and milestones',backup.format==='nucaloric-projects'&&backup.projects.length===2&&backup.projects.some(x=>x.tasks.some(t=>t.done)));
await p.locator('#atelierCommand').click();await p.locator('#deskCommandSearch').fill('terminal');await p.keyboard.press('Enter');check('command search opens the real terminal surface',await p.locator('#deskWork').getAttribute('data-focus')==='terminal'&&await p.locator('.cli-workspace').isVisible());await p.keyboard.press('Control+k');await p.keyboard.press('Escape');check('command palette closes without moving or resetting tool nodes',!await p.locator('#deskCommandPalette').evaluate(e=>e.open));
await p.locator('[data-desk-focus=ai]').click();await p.locator('#atelierFocus').click();check('focus mode gives the tool more room and excludes hidden context from tab order',!await p.locator('.atelier-context').isVisible()&&await p.locator('.atelier-context').evaluate(e=>e.inert));await p.keyboard.press('Escape');check('Escape restores the context panel',await p.locator('.atelier-context').isVisible()&&!await p.locator('.atelier-context').evaluate(e=>e.inert));
await p.keyboard.press('/');check('slash shortcut opens and focuses the visible library',await p.locator('#deskSearch').evaluate(e=>e===document.activeElement)&&await p.locator('.desk-library').isVisible());
check('reduced motion disables both dashboard motion controls',await p.locator('#atelierMotion').isDisabled()&&await p.locator('#deskMotion').isDisabled()&&await p.locator('body').evaluate(e=>e.classList.contains('desk-still')));
const moving=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'no-preference'}),m=await moving.newPage();m.on('pageerror',e=>errors.push(e.message));await m.goto(base+'/dashboard.html');await m.waitForFunction(()=>window.NUC_DESK_VIEW&&document.querySelector('.atelier-signal canvas').width>0);await m.locator('#atelierMotion').click();await m.waitForTimeout(100);const pixels=await m.locator('.atelier-signal canvas').evaluate(e=>e.toDataURL());await m.waitForTimeout(250);check('Pause stops the actual overview pixels and stays in sync with the rail',await m.evaluate(()=>NUC_DOTS.isPaused()&&document.body.classList.contains('desk-still'))&&await m.locator('#deskMotion').getAttribute('aria-pressed')==='true'&&await m.locator('.atelier-signal canvas').evaluate(e=>e.toDataURL())===pixels);await m.reload();await m.waitForFunction(()=>window.NUC_DESK_VIEW);check('dashboard motion preference survives reload',await m.locator('#atelierMotion').getAttribute('aria-pressed')==='true'&&await m.locator('#atelierMotion').innerText()==='Resume motion');await m.locator('#atelierMotion').click();check('Resume re-enables the shared renderer',await m.evaluate(()=>!NUC_DOTS.isPaused()&&!document.body.classList.contains('desk-still')));await moving.close();
const authenticated=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});const state=await fixture(authenticated),a=await authenticated.newPage();a.on('pageerror',e=>errors.push(e.message));await a.goto(base+'/dashboard.html');await a.waitForFunction(()=>window.NUC_DESK_VIEW&&window.NUC_TERMINAL?.session&&document.querySelector('#aiChatLog').textContent.includes('Start with one useful research workflow.'));
check('authenticated state keeps actual coin conversation and private controls',await a.locator('#aiWorkspace').isVisible()&&await a.locator('#atelierAccountLabel').innerText()==='Private account');const session=await a.evaluate(()=>NUC_TERMINAL.session);const opens=state.opened();
await a.locator('#aiQuestion').fill('A message kept while I inspect the project');await a.locator('#deskQuickKnowledge').click();await a.locator('[data-atelier-context=library]').click();await a.locator('#atelierFocus').click();await a.keyboard.press('Escape');check('context and focus changes preserve the unsent AI message',await a.locator('#aiQuestion').inputValue()==='A message kept while I inspect the project');
state.holdChat();await a.locator('#aiSend').click();while(!state.chatStarted())await a.waitForTimeout(25);await a.locator('[data-desk-focus=terminal]').click();await a.locator('[data-desk-open=connections]').click();check('active AI request stays pending while terminal and connections are used',await a.locator('#coinAI').getAttribute('aria-busy')==='true'&&await a.evaluate(()=>NUC_TERMINAL.session)===session&&state.opened()===opens);state.releaseChat();await a.locator('[data-desk-focus=ai]').click();await a.waitForFunction(()=>document.querySelector('#aiChatLog').textContent.includes('Your next step is ready to review.'));check('completed reply reaches the preserved conversation',await a.locator('.ai-message-assistant').count()===2);
await a.locator('.ai-message-assistant .ai-button').last().click();check('Save to knowledge opens the editor with the real reply',await a.locator('#deskManager').isVisible()&&await a.locator('#aiKnowledgeText').isVisible()&&await a.locator('#aiKnowledgeText').inputValue()==='Your next step is ready to review.');await a.locator('#aiKnowledgeSave').click();await a.waitForFunction(()=>document.querySelector('#aiKnowledgeList').textContent.includes('Your next step'));check('knowledge save retains its native request',state.requests.some(r=>r.path.endsWith('/knowledge')&&r.body.content==='Your next step is ready to review.'));
await a.locator('[data-desk-focus=terminal]').click();await a.locator('#cliLiveTerminal .xterm-helper-textarea').focus();await a.keyboard.type('echo review',{delay:10});await a.keyboard.press('Enter');await a.waitForTimeout(900);check('native terminal input still uses the owned session API',state.requests.some(r=>r.path.includes('shell/io')&&r.body.input&&Buffer.from(r.body.input,'base64').toString().includes('review')));
for(const width of [1920,1440,1280,1024,768,760,390,320]){await a.setViewportSize({width,height:1000});await a.locator('[data-desk-focus=ai]').click();await a.waitForTimeout(220);check('authenticated dashboard fits and keeps composer inside its panel at '+width+'px',await a.evaluate(()=>{const e=document.querySelector('#aiQuestion').getBoundingClientRect(),s=document.querySelector('.desk-canvas').getBoundingClientRect();return document.documentElement.scrollWidth===innerWidth&&e.width>150&&e.left>=s.left&&e.right<=s.right&&e.bottom<=s.bottom;}));await a.locator('[data-desk-focus=terminal]').click();await a.waitForTimeout(220);check('terminal fits and retains the same session at '+width+'px',await a.evaluate(id=>{const e=document.querySelector('#cliLiveTerminal').getBoundingClientRect(),s=document.querySelector('.desk-canvas').getBoundingClientRect();return NUC_TERMINAL.session===id&&e.width>100&&e.right<=s.right+1&&e.left>=s.left;},session));if([1440,390].includes(width))await a.screenshot({path:path.join(out,'terminal-'+width+'.png'),fullPage:true});}
check('resizing and switching never reconnects the preserved shell',state.opened()===opens&&state.requests.some(r=>r.path.includes('shell/resize')));
await a.setViewportSize({width:1440,height:1000});await a.locator('[data-desk-focus=ai]').click();await a.locator('[data-atelier-context=library]').click();await a.screenshot({path:path.join(out,'conversation-desktop.png'),fullPage:true});await a.setViewportSize({width:390,height:1000});await a.screenshot({path:path.join(out,'conversation-phone.png'),fullPage:true});await authenticated.close();
const blocked=await browser.newContext();await blocked.addInitScript(()=>{Storage.prototype.setItem=function(){throw Error('Storage unavailable');};});const bp=await blocked.newPage();await bp.goto(base+'/dashboard.html');await bp.waitForFunction(()=>window.NUC_DESK_VIEW);await bp.locator('#atelierNewProject').click();check('blocked storage explains failure without claiming a created project',(await bp.locator('#deskListStatus').innerText()).includes('Storage')&&await bp.evaluate(()=>NUC_PROJECTS.list().length===0));await blocked.close();
check('changed assets resolve',assets.length===0);check('no browser exceptions',errors.length===0);
}finally{fs.writeFileSync(path.join(out,'dashboard-validation.json'),JSON.stringify({checks,errors,assets},null,2));await browser.close();}
})().catch(e=>{console.error(e.stack);process.exitCode=1});
